project_id = "hmpwjhzrmfyapijikkuc"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.flitt-callback]
    verify_jwt = false
  [functions.preview-transactional-email]
    verify_jwt = false
  [functions.daily-tasks]
    verify_jwt = false
