// Static Business English vocabulary bank.
// Each word is keyed so progress can be tracked in Supabase by word_key.

export type VocabWord = {
  key: string;            // stable kebab-case id
  en: string;
  ka: string;
  explanationKa: string;
  pronunciation: string;  // simple ka phonetic guide
  exampleEn: string;
  exampleKa: string;
  example2En: string;
  example2Ka: string;
  source: "core" | "field";
  week?: number;          // for core words only
  field?: string;         // for field words
};

// ---------------- CORE CURRICULUM ----------------
// Week 1 foundational → Week 4 advanced. ~6-7 words per week.

export const CORE_WORDS: VocabWord[] = [
  // ---------- WEEK 1: foundations ----------
  {
    key: "deadline",
    en: "Deadline",
    ka: "ბოლო ვადა",
    explanationKa: "ბოლო თარიღი, რომელშიც დავალება უნდა დასრულდეს.",
    pronunciation: "დედლაინ",
    exampleEn: "We need to meet the deadline by Friday.",
    exampleKa: "პარასკევისთვის ვადა უნდა დავიცვათ.",
    example2En: "The deadline has been extended by one week.",
    example2Ka: "ვადა ერთი კვირით გადაიდო.",
    source: "core",
    week: 1,
  },
  {
    key: "client",
    en: "Client",
    ka: "კლიენტი",
    explanationKa: "ადამიანი ან კომპანია, რომელიც იყენებს თქვენს მომსახურებას.",
    pronunciation: "ქლაიენთ",
    exampleEn: "Our biggest client is based in Berlin.",
    exampleKa: "ჩვენი ყველაზე დიდი კლიენტი ბერლინშია.",
    example2En: "I have a call with the client at 3 PM.",
    example2Ka: "15:00-ზე ზარი მაქვს კლიენტთან.",
    source: "core",
    week: 1,
  },
  {
    key: "agenda",
    en: "Agenda",
    ka: "დღის წესრიგი",
    explanationKa: "შეხვედრის ან დღის გეგმა — რა საკითხები განიხილება.",
    pronunciation: "აჯენდა",
    exampleEn: "Let's stick to the agenda.",
    exampleKa: "მოდი დღის წესრიგს მივყვეთ.",
    example2En: "I'll send the agenda before the meeting.",
    example2Ka: "შეხვედრამდე დღის წესრიგს გამოვაგზავნი.",
    source: "core",
    week: 1,
  },
  {
    key: "feedback",
    en: "Feedback",
    ka: "უკუკავშირი",
    explanationKa: "მოსაზრება ან კომენტარი ვინმეს მუშაობაზე.",
    pronunciation: "ფიდბექ",
    exampleEn: "Thanks for the honest feedback on my report.",
    exampleKa: "გმადლობთ ჩემს ანგარიშზე გულახდილი უკუკავშირისთვის.",
    example2En: "I'd appreciate your feedback by tomorrow.",
    example2Ka: "თქვენი უკუკავშირი ხვალამდე მინდა.",
    source: "core",
    week: 1,
  },
  {
    key: "follow-up",
    en: "Follow up",
    ka: "გადამოწმება / დაკავშირება",
    explanationKa: "ხელახლა დაკავშირება საკითხის სტატუსის შესამოწმებლად.",
    pronunciation: "ფოლოუ აპ",
    exampleEn: "I'll follow up with the client next week.",
    exampleKa: "მომავალ კვირას კლიენტს დავუკავშირდები.",
    example2En: "Just following up on my previous email.",
    example2Ka: "უბრალოდ შეგახსენებთ ჩემს წინა იმეილს.",
    source: "core",
    week: 1,
  },
  {
    key: "schedule",
    en: "Schedule",
    ka: "გრაფიკი / დანიშვნა",
    explanationKa: "დროის გეგმა; ან ზმნა — დროის დანიშვნა.",
    pronunciation: "სქედჯულ",
    exampleEn: "Can we schedule a call for tomorrow?",
    exampleKa: "შეგვიძლია ხვალისთვის ზარი დავნიშნოთ?",
    example2En: "My schedule is tight this week.",
    example2Ka: "ამ კვირას გრაფიკი დატვირთული მაქვს.",
    source: "core",
    week: 1,
  },
  // ---------- WEEK 2: communication ----------
  {
    key: "stakeholder",
    en: "Stakeholder",
    ka: "დაინტერესებული მხარე",
    explanationKa: "ადამიანი ან ჯგუფი, რომელსაც აქვს ინტერესი პროექტში.",
    pronunciation: "სტეიქჰოლდერ",
    exampleEn: "We need to update all stakeholders weekly.",
    exampleKa: "კვირაში ერთხელ ყველა დაინტერესებულ მხარეს ვაცნობებთ.",
    example2En: "Key stakeholders approved the plan.",
    example2Ka: "ძირითადმა დაინტერესებულმა მხარეებმა გეგმა დაამტკიცეს.",
    source: "core",
    week: 2,
  },
  {
    key: "proposal",
    en: "Proposal",
    ka: "წინადადება",
    explanationKa: "ოფიციალური დოკუმენტი ან იდეა განსახილველად.",
    pronunciation: "პროპოუზალ",
    exampleEn: "I sent the proposal yesterday — let me know your thoughts.",
    exampleKa: "გუშინ წინადადება გამოვაგზავნე — შენი აზრი მაცნობე.",
    example2En: "The client accepted our proposal.",
    example2Ka: "კლიენტმა ჩვენი წინადადება მიიღო.",
    source: "core",
    week: 2,
  },
  {
    key: "revenue",
    en: "Revenue",
    ka: "შემოსავალი",
    explanationKa: "ფული, რომელსაც კომპანია იღებს გაყიდვებიდან.",
    pronunciation: "რევენიუ",
    exampleEn: "Revenue grew by 15% last quarter.",
    exampleKa: "შემოსავალი წინა კვარტალში 15%-ით გაიზარდა.",
    example2En: "We need to increase revenue.",
    example2Ka: "შემოსავალი უნდა გავზარდოთ.",
    source: "core",
    week: 2,
  },
  {
    key: "invoice",
    en: "Invoice",
    ka: "ანგარიშფაქტურა",
    explanationKa: "დოკუმენტი, რომელშიც ჩაწერილია გადასახდელი თანხა მომსახურებისთვის.",
    pronunciation: "ინვოის",
    exampleEn: "I'll send the invoice at the end of the month.",
    exampleKa: "ანგარიშფაქტურას თვის ბოლოს გამოვაგზავნი.",
    example2En: "Please pay the invoice within 14 days.",
    example2Ka: "გთხოვთ ანგარიში 14 დღეში გადაიხადოთ.",
    source: "core",
    week: 2,
  },
  {
    key: "deliver",
    en: "Deliver",
    ka: "ჩაბარება / შესრულება",
    explanationKa: "შეთანხმებული შედეგის ან პროდუქტის დროულად მიწოდება.",
    pronunciation: "დელივერ",
    exampleEn: "We always deliver on time.",
    exampleKa: "ჩვენ ყოველთვის დროულად ვაბარებთ.",
    example2En: "The team delivered great results.",
    example2Ka: "გუნდმა შესანიშნავი შედეგი მოიტანა.",
    source: "core",
    week: 2,
  },
  {
    key: "negotiate",
    en: "Negotiate",
    ka: "მოლაპარაკება",
    explanationKa: "შეთანხმებაზე მისვლა — განხილვა და კომპრომისი.",
    pronunciation: "ნეგოშიეით",
    exampleEn: "Let's negotiate the price next week.",
    exampleKa: "მომავალ კვირას ფასზე მოვილაპარაკოთ.",
    example2En: "She negotiated a better contract.",
    example2Ka: "მან უკეთეს კონტრაქტზე მოილაპარაკა.",
    source: "core",
    week: 2,
  },
  // ---------- WEEK 3: collaboration ----------
  {
    key: "presentation",
    en: "Presentation",
    ka: "პრეზენტაცია",
    explanationKa: "ფორმალური წარდგენა აუდიტორიის წინაშე.",
    pronunciation: "პრეზენტეიშენ",
    exampleEn: "My presentation is on Friday morning.",
    exampleKa: "ჩემი პრეზენტაცია პარასკევს დილით არის.",
    example2En: "Her presentation was clear and engaging.",
    example2Ka: "მისი პრეზენტაცია ნათელი და საინტერესო იყო.",
    source: "core",
    week: 3,
  },
  {
    key: "approve",
    en: "Approve",
    ka: "დამტკიცება",
    explanationKa: "ოფიციალური თანხმობის გაცემა რაიმეზე.",
    pronunciation: "ეფრუვ",
    exampleEn: "The manager approved the budget.",
    exampleKa: "მენეჯერმა ბიუჯეტი დაამტკიცა.",
    example2En: "Please approve the document by EOD.",
    example2Ka: "გთხოვთ დოკუმენტი დღის ბოლომდე დაამტკიცოთ.",
    source: "core",
    week: 3,
  },
  {
    key: "milestone",
    en: "Milestone",
    ka: "ეტაპი / ნიშნული",
    explanationKa: "მნიშვნელოვანი მიღწევა პროექტში.",
    pronunciation: "მაილსტოუნ",
    exampleEn: "We hit our first milestone last week.",
    exampleKa: "გასულ კვირას პირველ ეტაპს მივაღწიეთ.",
    example2En: "There are three milestones in this project.",
    example2Ka: "ამ პროექტში სამი ეტაპია.",
    source: "core",
    week: 3,
  },
  {
    key: "priority",
    en: "Priority",
    ka: "პრიორიტეტი",
    explanationKa: "ის, რაც სხვაზე უფრო მნიშვნელოვანი ან გადაუდებელია.",
    pronunciation: "პრაიორიტი",
    exampleEn: "This task is our top priority.",
    exampleKa: "ეს დავალება ჩვენი მთავარი პრიორიტეტია.",
    example2En: "Let's set clear priorities for the week.",
    example2Ka: "მოდი კვირის ნათელი პრიორიტეტები დავსახოთ.",
    source: "core",
    week: 3,
  },
  {
    key: "reschedule",
    en: "Reschedule",
    ka: "თარიღის შეცვლა",
    explanationKa: "უკვე დანიშნული შეხვედრის სხვა დროზე გადატანა.",
    pronunciation: "რისქედჯულ",
    exampleEn: "Can we reschedule for Thursday?",
    exampleKa: "შეგვიძლია ხუთშაბათისთვის გადავიტანოთ?",
    example2En: "I had to reschedule the meeting.",
    example2Ka: "შეხვედრის გადატანა მომიწია.",
    source: "core",
    week: 3,
  },
  {
    key: "summary",
    en: "Summary",
    ka: "შეჯამება",
    explanationKa: "მოკლე მიმოხილვა მნიშვნელოვანი ინფორმაციისა.",
    pronunciation: "სამარი",
    exampleEn: "Here's a quick summary of the meeting.",
    exampleKa: "აი შეხვედრის სწრაფი შეჯამება.",
    example2En: "I'll send a summary by email.",
    example2Ka: "შეჯამებას იმეილით გამოვაგზავნი.",
    source: "core",
    week: 3,
  },
  // ---------- WEEK 4: nuance ----------
  {
    key: "leverage",
    en: "Leverage",
    ka: "გამოყენება / ბერკეტი",
    explanationKa: "რესურსის ან უპირატესობის ეფექტურად გამოყენება.",
    pronunciation: "ლევერიჯ",
    exampleEn: "We can leverage our network to find clients.",
    exampleKa: "კლიენტების მოსაძებნად ჩვენი კონტაქტები შეგვიძლია გამოვიყენოთ.",
    example2En: "Leverage your strengths in the interview.",
    example2Ka: "გასაუბრებაზე ძლიერი მხარეები გამოიყენე.",
    source: "core",
    week: 4,
  },
  {
    key: "scope",
    en: "Scope",
    ka: "ფარგლები / მოცულობა",
    explanationKa: "პროექტის ფარგლები — რა შედის და რა არ შედის.",
    pronunciation: "სქოუპ",
    exampleEn: "That's outside the scope of this project.",
    exampleKa: "ეს ამ პროექტის ფარგლებს გარეთაა.",
    example2En: "Let's define the scope clearly.",
    example2Ka: "მოდი ფარგლები მკაფიოდ განვსაზღვროთ.",
    source: "core",
    week: 4,
  },
  {
    key: "align",
    en: "Align",
    ka: "შეთანხმება / გასწორება",
    explanationKa: "მიზნებზე ან გეგმაზე ერთიანი ხედვის გამომუშავება.",
    pronunciation: "ელაინ",
    exampleEn: "Let's align on the next steps.",
    exampleKa: "მოდი შემდეგ ნაბიჯებზე შევთანხმდეთ.",
    example2En: "Our team is fully aligned on the goals.",
    example2Ka: "ჩვენი გუნდი მიზნებზე სრულად შეთანხმებულია.",
    source: "core",
    week: 4,
  },
  {
    key: "scalable",
    en: "Scalable",
    ka: "მასშტაბირებადი",
    explanationKa: "ისეთი სისტემა ან გადაწყვეტა, რომელიც ზრდას უძლებს.",
    pronunciation: "სქეილებლ",
    exampleEn: "We need a scalable solution.",
    exampleKa: "მასშტაბირებადი გადაწყვეტა გვჭირდება.",
    example2En: "This process isn't scalable for a bigger team.",
    example2Ka: "ეს პროცესი დიდი გუნდისთვის ვერ გაფართოვდება.",
    source: "core",
    week: 4,
  },
  {
    key: "onboarding",
    en: "Onboarding",
    ka: "ადაპტაცია (ახალი თანამშრომლის)",
    explanationKa: "პროცესი, რომლის დროსაც ახალი თანამშრომელი ეცნობა კომპანიას.",
    pronunciation: "ონბორდინგ",
    exampleEn: "Onboarding usually takes two weeks.",
    exampleKa: "ადაპტაცია ჩვეულებრივ ორ კვირას გრძელდება.",
    example2En: "She's still in onboarding.",
    example2Ka: "ის ჯერ კიდევ ადაპტაციის პერიოდშია.",
    source: "core",
    week: 4,
  },
  {
    key: "outcome",
    en: "Outcome",
    ka: "შედეგი",
    explanationKa: "ქმედების ან პროცესის საბოლოო შედეგი.",
    pronunciation: "აუთქამ",
    exampleEn: "We're happy with the outcome.",
    exampleKa: "შედეგით კმაყოფილი ვართ.",
    example2En: "The outcome of the meeting was positive.",
    example2Ka: "შეხვედრის შედეგი დადებითი იყო.",
    source: "core",
    week: 4,
  },
];

// ---------------- FIELD-SPECIFIC WORDS ----------------

export const FIELD_WORDS: VocabWord[] = [
  // freelance / remote
  {
    key: "retainer",
    en: "Retainer",
    ka: "ყოველთვიური საფასური",
    explanationKa: "ფიქსირებული თანხა, რომელსაც კლიენტი ყოველთვიურად იხდის უწყვეტი მომსახურებისთვის.",
    pronunciation: "რიტეინერ",
    exampleEn: "We work on a monthly retainer.",
    exampleKa: "ვმუშაობთ ყოველთვიური საფასურით.",
    example2En: "The retainer covers up to 20 hours.",
    example2Ka: "საფასური 20 საათამდე მუშაობას ფარავს.",
    source: "field",
    field: "remote_work",
  },
  {
    key: "deliverable",
    en: "Deliverable",
    ka: "მისატანი შედეგი",
    explanationKa: "კონკრეტული პროდუქტი ან დოკუმენტი, რომელიც კლიენტს უნდა ჩაბარდეს.",
    pronunciation: "დელივერებლ",
    exampleEn: "The main deliverable is the final report.",
    exampleKa: "მთავარი მისატანი შედეგი საბოლოო ანგარიშია.",
    example2En: "Here's the list of deliverables for phase 1.",
    example2Ka: "აი პირველი ფაზის შედეგების სია.",
    source: "field",
    field: "remote_work",
  },
  {
    key: "brief",
    en: "Brief",
    ka: "ბრიფი / დავალება",
    explanationKa: "მოკლე დოკუმენტი, რომელშიც კლიენტი აღწერს რა სჭირდება.",
    pronunciation: "ბრიფ",
    exampleEn: "Please send me the project brief.",
    exampleKa: "გთხოვ პროექტის ბრიფი გამომიგზავნე.",
    example2En: "The brief is unclear — I'll ask questions.",
    example2Ka: "ბრიფი არ არის ნათელი — შეკითხვებს დავსვამ.",
    source: "field",
    field: "remote_work",
  },
  // management
  {
    key: "delegation",
    en: "Delegation",
    ka: "დელეგირება",
    explanationKa: "დავალების სხვისთვის გადაცემა შესაბამისი პასუხისმგებლობით.",
    pronunciation: "დელეგეიშენ",
    exampleEn: "Good delegation frees up time for strategy.",
    exampleKa: "კარგი დელეგირება სტრატეგიისთვის დროს ათავისუფლებს.",
    example2En: "She struggles with delegation.",
    example2Ka: "მას უჭირს დელეგირება.",
    source: "field",
    field: "management",
  },
  {
    key: "kpi",
    en: "KPI",
    ka: "ეფექტურობის საზომი",
    explanationKa: "Key Performance Indicator — ციფრი, რომელიც აჩვენებს რამდენად კარგად მუშაობს ვინმე ან რამე.",
    pronunciation: "ქეი პი აი",
    exampleEn: "Let's review the team's KPIs.",
    exampleKa: "გუნდის KPI-ებს მიმოვიხილავთ.",
    example2En: "This KPI dropped last month.",
    example2Ka: "ეს KPI გასულ თვეს დაეცა.",
    source: "field",
    field: "management",
  },
  {
    key: "accountability",
    en: "Accountability",
    ka: "ანგარიშვალდებულება",
    explanationKa: "თქვენი ქმედებების შედეგებზე პასუხის გაცემის მზადყოფნა.",
    pronunciation: "ექაუნთებილითი",
    exampleEn: "We value accountability on this team.",
    exampleKa: "ჩვენს გუნდში ანგარიშვალდებულება ფასობს.",
    example2En: "Who has accountability for this?",
    example2Ka: "ვის ეკისრება ამაზე ანგარიშვალდებულება?",
    source: "field",
    field: "management",
  },
  // marketing
  {
    key: "campaign",
    en: "Campaign",
    ka: "კამპანია",
    explanationKa: "მარკეტინგული აქტივობების კოორდინირებული სერია კონკრეტული მიზნისთვის.",
    pronunciation: "ქემფეინ",
    exampleEn: "Our summer campaign launches in June.",
    exampleKa: "ჩვენი ზაფხულის კამპანია ივნისში იწყება.",
    example2En: "The campaign exceeded expectations.",
    example2Ka: "კამპანიამ მოლოდინი გადააჭარბა.",
    source: "field",
    field: "marketing",
  },
  {
    key: "engagement",
    en: "Engagement",
    ka: "ჩართულობა",
    explanationKa: "რამდენად აქტიურად რეაგირებს აუდიტორია თქვენს კონტენტზე.",
    pronunciation: "ენგეიჯმენთ",
    exampleEn: "Engagement is up 20% this month.",
    exampleKa: "ამ თვეში ჩართულობა 20%-ით გაიზარდა.",
    example2En: "Stories drive more engagement than posts.",
    example2Ka: "სთორიები პოსტებზე მეტ ჩართულობას იძლევა.",
    source: "field",
    field: "marketing",
  },
  {
    key: "conversion-rate",
    en: "Conversion",
    ka: "კონვერსია",
    explanationKa: "მომხმარებლის ქმედება, რომელიც სასურველ შედეგამდე მიდის (მაგ. ყიდვა).",
    pronunciation: "ქონვერჟენ",
    exampleEn: "The new landing page improved conversions.",
    exampleKa: "ახალმა landing page-მა კონვერსიები გააუმჯობესა.",
    example2En: "Our conversion rate is 3%.",
    example2Ka: "ჩვენი კონვერსიის მაჩვენებელი 3%-ია.",
    source: "field",
    field: "marketing",
  },
  // sales
  {
    key: "pipeline",
    en: "Pipeline",
    ka: "გაყიდვების პაიპლაინი",
    explanationKa: "მომავალი გაყიდვების შესაძლებლობების ნაკადი.",
    pronunciation: "ფაიფლაინ",
    exampleEn: "Our pipeline looks strong for Q3.",
    exampleKa: "ჩვენი pipeline მესამე კვარტალისთვის ძლიერია.",
    example2En: "We need to fill the pipeline with new leads.",
    example2Ka: "pipeline-ი ახალი ლიდებით უნდა შევავსოთ.",
    source: "field",
    field: "sales",
  },
  // finance
  {
    key: "sales-forecast",
    en: "Forecast",
    ka: "პროგნოზი",
    explanationKa: "მომავალი შემოსავლის ან ხარჯის სავარაუდო შეფასება.",
    pronunciation: "ფორქასტ",
    exampleEn: "The forecast for next quarter is positive.",
    exampleKa: "მომდევნო კვარტლის პროგნოზი დადებითია.",
    example2En: "We revised our sales forecast.",
    example2Ka: "გაყიდვების პროგნოზს გადავხედეთ.",
    source: "field",
    field: "finance",
  },
  // project management
  {
    key: "blocker",
    en: "Blocker",
    ka: "შემაფერხებელი",
    explanationKa: "პრობლემა, რომელიც დავალების შესრულებას აფერხებს.",
    pronunciation: "ბლოქერ",
    exampleEn: "I have one blocker — waiting on design.",
    exampleKa: "ერთი შემაფერხებელი მაქვს — დიზაინს ველოდები.",
    example2En: "Let's solve this blocker today.",
    example2Ka: "მოდი დღეს ეს შემაფერხებელი მოვაგვაროთ.",
    source: "field",
    field: "project_management",
  },
];

// ---------------- COMPACT TIER EXPANSIONS ----------------
// Helper to keep tier definitions readable.
type Mini = [string, string, string, string, string]; // key, en, ka, exampleEn, exampleKa
const mk = (m: Mini, week: number): VocabWord => ({
  key: m[0], en: m[1], ka: m[2],
  explanationKa: "",
  pronunciation: "",
  exampleEn: m[3], exampleKa: m[4],
  example2En: "", example2Ka: "",
  source: "core",
  week,
});
const mkField = (m: Mini, field: string): VocabWord => ({
  key: m[0], en: m[1], ka: m[2],
  explanationKa: "",
  pronunciation: "",
  exampleEn: m[3], exampleKa: m[4],
  example2En: "", example2Ka: "",
  source: "field",
  field,
});

// ---- TIER 1: Foundation (weeks 1-3, generic everyday business) ----
const TIER1: Mini[] = [
  ["meeting","Meeting","შეხვედრა","We have a meeting at 10.","შეხვედრა გვაქვს 10-ზე."],
  ["report","Report","ანგარიში / მოხსენება","Please send the report.","გთხოვ ანგარიში გამოგზავნე."],
  ["budget","Budget","ბიუჯეტი","The budget is tight.","ბიუჯეტი მცირეა."],
  ["contract","Contract","კონტრაქტი","We signed the contract.","ხელშეკრულება გავაფორმეთ."],
  ["payment","Payment","გადახდა","Payment is due in 30 days.","გადახდის ვადა 30 დღეა."],
  ["update","Update","განახლება","I have an update for you.","განახლება მაქვს შენთვის."],
  ["confirm","Confirm","დადასტურება","Please confirm by email.","გთხოვ იმეილით დაადასტურე."],
  ["cancel","Cancel","გაუქმება","We had to cancel the call.","ზარის გაუქმება მოგვიწია."],
  ["postpone","Postpone","გადადება","Let's postpone the meeting.","შეხვედრა გადავდოთ."],
  ["attend","Attend","დასწრება","I can't attend tomorrow.","ხვალ ვერ დავესწრები."],
  ["host","Host","მასპინძლობა","She will host the call.","ის უმასპინძლებს ზარს."],
  ["join","Join","შეერთება","Please join the call.","გთხოვ შემოუერთდი ზარს."],
  ["share","Share","გაზიარება","Can you share your screen?","შეგიძლია ეკრანი გააზიარო?"],
  ["send","Send","გაგზავნა","I'll send it shortly.","მალე გავაგზავნი."],
  ["receive","Receive","მიღება","Did you receive my email?","მიიღე ჩემი იმეილი?"],
  ["reply","Reply","პასუხის გაცემა","I'll reply by EOD.","დღის ბოლომდე ვუპასუხებ."],
  ["forward","Forward","გადაგზავნა","I'll forward it to you.","გადმოგიგზავნი."],
  ["attach","Attach","მიმაგრება","Please attach the file.","გთხოვ ფაილი მიამაგრე."],
  ["file","File","ფაილი","The file is too large.","ფაილი ძალიან დიდია."],
  ["folder","Folder","საქაღალდე","Check the shared folder.","გადახედე საერთო საქაღალდეს."],
  ["link","Link","ბმული","Here's the link.","აი ბმული."],
  ["copy","Copy","ასლი","Please copy me on the email.","გთხოვ ასლი მეც გამომიგზავნე."],
  ["bcc","BCC","ფარული ასლი","Add HR in BCC.","HR ფარულ ასლში დაამატე."],
  ["subject","Subject","თემა","Clear subject helps.","მკაფიო თემა ეხმარება."],
  ["draft","Draft","მონახაზი / შავი ვერსია","I'll draft the email.","იმეილის მონახაზს მოვამზადებ."],
  ["sign","Sign","ხელის მოწერა","Please sign the contract.","გთხოვ კონტრაქტს ხელი მოაწერე."],
  ["reject","Reject","უარყოფა","They rejected the offer.","შეთავაზება უარყვეს."],
  ["review","Review","გადახედვა","Let's review the document.","დოკუმენტი გადავხედოთ."],
  ["edit","Edit","რედაქტირება","Edit the draft, please.","გთხოვ მონახაზი დაარედაქტირე."],
  ["finalize","Finalize","საბოლოო დასრულება","Let's finalize this today.","დღეს ეს დავასრულოთ."],
  ["submit","Submit","ჩაბარება / გაგზავნა (ოფიციალურად)","Submit it before Friday.","პარასკევამდე წარადგინე."],
  ["request","Request","მოთხოვნა","I have a small request.","პატარა მოთხოვნა მაქვს."],
  ["respond","Respond","რეაგირება","Respond as soon as possible.","რაც შეიძლება მალე უპასუხე."],
  ["explain","Explain","ახსნა","Can you explain again?","ხელახლა ამიხსნი?"],
  ["clarify","Clarify","გარკვევა","Let me clarify.","ნება მომეცი დავაზუსტო."],
  ["question","Question","კითხვა","I have a question.","შეკითხვა მაქვს."],
  ["answer","Answer","პასუხი","Here's my answer.","აი ჩემი პასუხი."],
  ["task","Task","დავალება","I have many tasks today.","დღეს ბევრი დავალება მაქვს."],
  ["goal","Goal","მიზანი","Our goal is clear.","ჩვენი მიზანი მკაფიოა."],
  ["plan","Plan","გეგმა","What's the plan?","რა გეგმაა?"],
  ["progress","Progress","პროგრესი","We're making progress.","პროგრესს ვაკეთებთ."],
  ["status","Status","სტატუსი","What's the status?","რა სტატუსია?"],
  ["urgent","Urgent","გადაუდებელი","It's urgent.","გადაუდებელია."],
  ["important","Important","მნიშვნელოვანი","This is very important.","ეს ძალიან მნიშვნელოვანია."],
  ["available","Available","თავისუფალი / ხელმისაწვდომი","Are you available now?","ახლა თავისუფალი ხარ?"],
  ["busy","Busy","დაკავებული","I'm busy until 3.","3-მდე დაკავებული ვარ."],
  ["free","Free","თავისუფალი","I'm free after lunch.","ლანჩის შემდეგ თავისუფალი ვარ."],
  ["office","Office","ოფისი","I'm in the office.","ოფისში ვარ."],
  ["remote","Remote","დისტანციური","I work remote on Fridays.","პარასკევობით დისტანციურად ვმუშაობ."],
  ["hybrid","Hybrid","ჰიბრიდი","We have a hybrid model.","ჰიბრიდული მოდელი გვაქვს."],
  ["team","Team","გუნდი","Our team is great.","ჩვენი გუნდი მაგარია."],
  ["department","Department","დეპარტამენტი","She runs the HR department.","ის HR დეპარტამენტს ხელმძღვანელობს."],
  ["manager","Manager","მენეჯერი","My manager approved it.","ჩემმა მენეჯერმა დაამტკიცა."],
  ["boss","Boss","უფროსი","My boss is on vacation.","ჩემი უფროსი შვებულებაშია."],
  ["colleague","Colleague","კოლეგა","She's a great colleague.","ის მაგარი კოლეგაა."],
  ["employee","Employee","თანამშრომელი","We hired three employees.","სამი თანამშრომელი ავიყვანეთ."],
  ["company","Company","კომპანია","The company is growing.","კომპანია იზრდება."],
  ["customer","Customer","მომხმარებელი","The customer is happy.","მომხმარებელი კმაყოფილია."],
  ["vendor","Vendor","მომწოდებელი","Our vendor delivers on time.","ჩვენი მომწოდებელი დროულად ამარაგებს."],
  ["supplier","Supplier","მომმარაგებელი","We changed suppliers.","მომმარაგებლები შევცვალეთ."],
  ["partner","Partner","პარტნიორი","They are our partner.","ისინი ჩვენი პარტნიორები არიან."],
  ["service","Service","სერვისი","We offer good service.","კარგ სერვისს ვთავაზობთ."],
  ["product","Product","პროდუქტი","Our product is unique.","ჩვენი პროდუქტი უნიკალურია."],
  ["price","Price","ფასი","What's the price?","რა ფასია?"],
  ["cost","Cost","ღირებულება","The cost is too high.","ღირებულება ძალიან მაღალია."],
  ["fee","Fee","საფასური","There's a small fee.","მცირე საფასურია."],
  ["discount","Discount","ფასდაკლება","We offer a discount.","ფასდაკლებას ვთავაზობთ."],
  ["offer","Offer","შეთავაზება","Here's our offer.","აი ჩვენი შეთავაზება."],
  ["deal","Deal","გარიგება","We closed the deal.","გარიგება დავხურეთ."],
  ["sale","Sale","გაყიდვა","Sales are up this month.","ამ თვეში გაყიდვები გაიზარდა."],
  ["target","Target","სამიზნე","We hit the target.","სამიზნეს მივაღწიეთ."],
  ["growth","Growth","ზრდა","Growth is steady.","ზრდა მდგრადია."],
  ["profit","Profit","მოგება","We made a profit.","მოგება მივიღეთ."],
  ["loss","Loss","ზარალი","We had a small loss.","მცირე ზარალი გვქონდა."],
  ["expense","Expense","ხარჯი","This is a big expense.","ეს დიდი ხარჯია."],
  ["payment-terms","Payment terms","გადახდის პირობები","What are your payment terms?","რა გადახდის პირობები გაქვთ?"],
  ["due","Due","ვადა","Payment is due Monday.","გადახდის ვადა ორშაბათია."],
  ["quote","Quote","ფასის შეთავაზება","Can I get a quote?","შეიძლება ფასის შეთავაზება მივიღო?"],
  ["estimate","Estimate","წინასწარი შეფასება","Here's my estimate.","აი ჩემი შეფასება."],
  ["bill","Bill","გადასახდელი ანგარიში","I paid the bill.","ანგარიში გადავიხადე."],
  ["receipt","Receipt","ქვითარი","Send me the receipt.","ქვითარი გამომიგზავნე."],
  ["account","Account","ანგარიში (საბანკო)","Check your account.","ანგარიში გადაამოწმე."],
  ["balance","Balance","ნაშთი","Check the balance.","ნაშთი გადაამოწმე."],
  ["transfer","Transfer","გადარიცხვა","I'll transfer the funds.","თანხას გადავრიცხავ."],
  ["refund","Refund","თანხის დაბრუნება","Can I get a refund?","შეიძლება თანხა დამიბრუნდეს?"],
  ["question-time","Q&A","კითხვა-პასუხი","We'll have Q&A at the end.","ბოლოს კითხვა-პასუხი იქნება."],
  ["minutes","Minutes","ოქმი","I'll take the minutes.","ოქმს მე ვაწერ."],
  ["notes","Notes","ჩანაწერები","Share the notes after.","ჩანაწერები შემდეგ გააზიარე."],
  ["overview","Overview","მიმოხილვა","Here's an overview.","აი მიმოხილვა."],
  ["intro","Introduction","გაცნობა","Let me start with an intro.","გაცნობით დავიწყებ."],
  ["welcome","Welcome","კეთილი იყოს მობრძანება","Welcome to the team!","კეთილი იყოს მობრძანება გუნდში!"],
  ["thanks","Thanks","გმადლობთ","Thanks for your help.","გმადლობთ დახმარებისთვის."],
  ["regards","Regards","პატივისცემით","Best regards, John.","პატივისცემით, ჯონ."],
  ["lunch","Lunch","ლანჩი","Lunch is at 1 PM.","ლანჩი 13:00-ზეა."],
  ["break","Break","შესვენება","Let's take a 10-min break.","10-წუთიანი შესვენება ავიღოთ."],
  ["holiday","Holiday","უქმე დღე","Monday is a holiday.","ორშაბათი უქმე დღეა."],
  ["vacation","Vacation","შვებულება","I'm on vacation next week.","მომავალ კვირას შვებულებაში ვარ."],
  ["leave","Leave","შვებულება / გასვლა","I'm on sick leave.","ავადმყოფობის შვებულებაში ვარ."],
  ["overtime","Overtime","ზეგანაკვეთური","I worked overtime.","ზეგანაკვეთურად ვიმუშავე."],
  ["shift","Shift","ცვლა","My shift starts at 9.","ჩემი ცვლა 9-ზე იწყება."],
  ["call","Call","ზარი","Let's hop on a call.","მოდი ზარზე გადავიდეთ."],
  ["chat","Chat","ჩატი","Let's chat tomorrow.","ხვალ მოვილაპარაკოთ."],
  ["meet","Meet","შეხვედრა (ზმნა)","Let's meet at 3.","3-ზე შევხვდეთ."],
  ["greet","Greet","მისალმება","Greet the new hire.","ახალ თანამშრომელს მიესალმე."],
  ["discuss","Discuss","განხილვა","We'll discuss it later.","შემდეგ განვიხილავთ."],
  ["decide","Decide","გადაწყვეტილების მიღება","We need to decide today.","დღეს უნდა გადავწყვიტოთ."],
  ["agree","Agree","დათანხმება","I agree with you.","გეთანხმები."],
  ["disagree","Disagree","არ შეთანხმება","I respectfully disagree.","პატივისცემით არ ვეთანხმები."],
  ["suggest","Suggest","შემოთავაზება","I suggest we wait.","გთავაზობ მოვიცადოთ."],
  ["recommend","Recommend","რეკომენდაცია","I recommend this approach.","ამ მიდგომას გირჩევ."],
  ["help","Help","დახმარება","Can you help me?","შეგიძლია დამეხმარო?"],
  ["support","Support","მხარდაჭერა","Thanks for the support.","გმადლობთ მხარდაჭერისთვის."],
  ["issue","Issue","საკითხი / პრობლემა","We have an issue.","პრობლემა გვაქვს."],
  ["problem","Problem","პრობლემა","No problem.","არანაირი პრობლემა."],
  ["solution","Solution","გამოსავალი","I have a solution.","გადაწყვეტა მაქვს."],
  ["fix","Fix","გასწორება","I'll fix it today.","დღეს გავასწორებ."],
  ["check","Check","შემოწმება","Let me check.","ერთი შევამოწმო."],
  ["test","Test","ტესტი","We need to test it.","უნდა გავტესტოთ."],
  ["try","Try","ცდა","Let's try again.","კიდევ ვცადოთ."],
  ["work","Work","სამუშაო","I have a lot of work.","ბევრი სამუშაო მაქვს."],
  ["job","Job","სამსახური","I love my job.","ჩემი სამსახური მიყვარს."],
  ["role","Role","როლი","What's your role?","რა როლი გაქვს?"],
  ["responsibility","Responsibility","პასუხისმგებლობა","That's my responsibility.","ეს ჩემი პასუხისმგებლობაა."],
  ["duty","Duty","მოვალეობა","It's part of my duties.","მოვალეობების ნაწილია."],
  ["skill","Skill","უნარი","Good communication is a key skill.","კარგი კომუნიკაცია მთავარი უნარია."],
  ["experience","Experience","გამოცდილება","I have 5 years of experience.","5 წლის გამოცდილება მაქვს."],
  ["training","Training","ტრენინგი","Training starts next week.","ტრენინგი მომავალ კვირას იწყება."],
  ["learn","Learn","სწავლა","I learn every day.","ყოველდღე ვსწავლობ."],
  ["teach","Teach","სწავლება","She teaches new hires.","ის ახალ თანამშრომლებს ასწავლის."],
  ["mentor","Mentor","მენტორი","He's my mentor.","ის ჩემი მენტორია."],
  // --- Batch 1 expansion: everyday business essentials ---
  ["inbox","Inbox","ინბოქსი / შემომავალი წერილები","My inbox is full.","ჩემი ინბოქსი სავსეა."],
  ["attachment","Attachment","მიმაგრებული ფაილი","See the attachment.","იხილე მიმაგრებული ფაილი."],
  ["recipient","Recipient","მიმღები","Check the recipient before sending.","გაგზავნამდე მიმღები გადაამოწმე."],
  ["sender","Sender","გამომგზავნი","Who is the sender?","ვინ არის გამომგზავნი?"],
  ["signature","Signature","იმეილის ხელმოწერა","Add your email signature.","იმეილს ხელმოწერა დაამატე."],
  ["template","Template","შაბლონი","Use the report template.","ანგარიშის შაბლონი გამოიყენე."],
  ["form","Form","ფორმა","Fill out the form.","ფორმა შეავსე."],
  ["checklist","Checklist","ჩამონათვალი","Follow the checklist.","ჩამონათვალს მიჰყევი."],
  ["document","Document","დოკუმენტი","Sign the document.","დოკუმენტს ხელი მოაწერე."],
  ["spreadsheet","Spreadsheet","ელექტრონული ცხრილი","Update the spreadsheet.","ცხრილი განაახლე."],
  ["slide","Slide","სლაიდი","Add one more slide.","კიდევ ერთი სლაიდი დაამატე."],
  ["version","Version","ვერსია","Send the latest version.","ბოლო ვერსია გამოაგზავნე."],
  ["typo","Typo","ბეჭდვითი შეცდომა","Fix the typo on page two.","მეორე გვერდზე ბეჭდვითი შეცდომა გაასწორე."],
  ["proofread","Proofread","კორექტურა / გადაკითხვა","Proofread before sending.","გაგზავნამდე გადაიკითხე."],
  ["print","Print","ამობეჭდვა","Print two copies.","ორი ასლი ამობეჭდე."],
  ["scan","Scan","დასკანერება","Scan the contract.","კონტრაქტი დაასკანერე."],
  ["upload","Upload","ატვირთვა","Upload the file here.","ფაილი აქ ატვირთე."],
  ["download","Download","ჩამოტვირთვა","Download the report.","ანგარიში ჩამოტვირთე."],
  ["save","Save","შენახვა","Save your changes.","ცვლილებები შეინახე."],
  ["delete","Delete","წაშლა","Delete the old draft.","ძველი მონახაზი წაშალე."],
  ["rename","Rename","გადარქმევა","Rename the folder.","საქაღალდეს სახელი გადაარქვი."],
  ["archive","Archive","არქივი / დაარქივება","Archive old emails.","ძველი იმეილები დააარქივე."],
  ["cc","CC","ღია ასლი","CC the manager, please.","გთხოვ მენეჯერი ღია ასლში დაამატე."],
  ["reminder","Reminder","შემახსენებელი","Set a reminder.","შემახსენებელი დააყენე."],
  ["notification","Notification","შეტყობინება","Turn on notifications.","შეტყობინებები ჩართე."],
  ["message","Message","მესიჯი","I got your message.","შენი მესიჯი მივიღე."],
  ["calendar","Calendar","კალენდარი","Check my calendar.","ჩემი კალენდარი ნახე."],
  ["appointment","Appointment","დანიშნული შეხვედრა","I have an appointment at noon.","შუადღეს დანიშნული შეხვედრა მაქვს."],
  ["invite","Invite","მოწვევა","Send a calendar invite.","კალენდრის მოწვევა გააგზავნე."],
  ["attendee","Attendee","დამსწრე","Ten attendees joined.","ათი დამსწრე შემოუერთდა."],
  ["participant","Participant","მონაწილე","All participants agreed.","ყველა მონაწილე დათანხმდა."],
  ["organizer","Organizer","ორგანიზატორი","Ask the organizer.","ორგანიზატორს ჰკითხე."],
  ["availability","Availability","ხელმისაწვდომი დრო","Share your availability.","შენი თავისუფალი დროები გამიზიარე."],
  ["venue","Venue","ჩატარების ადგილი","The venue changed.","ჩატარების ადგილი შეიცვალა."],
  ["meeting-room","Meeting room","საკონფერენციო ოთახი","Book a meeting room.","საკონფერენციო ოთახი დაჯავშნე."],
  ["book","Book (reserve)","დაჯავშნა","Book the room for 3 PM.","ოთახი 3 საათზე დაჯავშნე."],
  ["staff","Staff","პერსონალი","Our staff is growing.","ჩვენი პერსონალი იზრდება."],
  ["intern","Intern","სტაჟიორი","The intern starts Monday.","სტაჟიორი ორშაბათს იწყებს."],
  ["supervisor","Supervisor","უშუალო ხელმძღვანელი","Ask your supervisor.","შენს ხელმძღვანელს ჰკითხე."],
  ["assistant","Assistant","ასისტენტი","My assistant will confirm.","ჩემი ასისტენტი დაადასტურებს."],
  ["director","Director","დირექტორი","She's the marketing director.","ის მარკეტინგის დირექტორია."],
  ["executive","Executive","აღმასრულებელი","An executive decision.","აღმასრულებელი გადაწყვეტილება."],
  ["founder","Founder","დამფუძნებელი","The founder spoke first.","პირველად დამფუძნებელმა ისაუბრა."],
  ["owner","Owner","მფლობელი","The owner approved it.","მფლობელმა დაამტკიცა."],
  ["branch","Branch","ფილიალი","We opened a new branch.","ახალი ფილიალი გავხსენით."],
  ["headquarters","Headquarters","სათავო ოფისი","Headquarters is in Tbilisi.","სათავო ოფისი თბილისშია."],
  ["division","Division","სამმართველო","He leads the sales division.","ის გაყიდვების სამმართველოს ხელმძღვანელობს."],
  ["position","Position","პოზიცია","I applied for the position.","ამ პოზიციაზე განაცხადი შევიტანე."],
  ["resign","Resign","გადადგომა","He resigned last week.","ის გასულ კვირას გადადგა."],
  ["retire","Retire","პენსიაზე გასვლა","She retires next year.","ის მომავალ წელს პენსიაზე გადის."],
  ["hire","Hire","აყვანა (სამსახურში)","We're hiring two designers.","ორ დიზაინერს ვიყვანთ სამსახურში."],
  ["fire","Fire (dismiss)","სამსახურიდან გათავისუფლება","They fired the contractor.","კონტრაქტორი გაათავისუფლეს."],
  ["apply","Apply","განაცხადის შეტანა","Apply by Friday.","პარასკევამდე შეიტანე განაცხადი."],
  ["application","Application","განაცხადი","We got 40 applications.","40 განაცხადი მივიღეთ."],
  ["cv","CV / Resume","რეზიუმე","Send your CV.","შენი რეზიუმე გამოაგზავნე."],
  ["reference","Reference","რეკომენდატორი","Can I list you as a reference?","შემიძლია რეკომენდატორად მიგითითო?"],
  ["probation","Probation","გამოსაცდელი ვადა","Three-month probation period.","სამთვიანი გამოსაცდელი ვადა."],
  ["quarter","Quarter","კვარტალი","Sales grew this quarter.","ამ კვარტალში გაყიდვები გაიზარდა."],
  ["fiscal-year","Fiscal year","ფისკალური წელი","The fiscal year ends in June.","ფისკალური წელი ივნისში მთავრდება."],
  ["annual","Annual","წლიური","The annual report is out.","წლიური ანგარიში გამოვიდა."],
  ["monthly","Monthly","ყოველთვიური","A monthly summary.","ყოველთვიური შეჯამება."],
  ["weekly","Weekly","ყოველკვირეული","Our weekly team meeting.","ჩვენი ყოველკვირეული შეხვედრა."],
  ["daily","Daily","ყოველდღიური","Daily standup at 10.","ყოველდღიური სტენდაფი 10 საათზე."],
  ["extension","Extension","ვადის გაგრძელება","Can we get an extension?","შეგვიძლია ვადის გაგრძელება?"],
  ["delay","Delay","შეფერხება / დაგვიანება","There's a two-day delay.","ორდღიანი შეფერხებაა."],
  ["ahead-of-schedule","Ahead of schedule","გრაფიკზე ადრე","We're ahead of schedule.","გრაფიკს ვუსწრებთ."],
  ["behind-schedule","Behind schedule","გრაფიკს ჩამორჩენილი","We're two weeks behind schedule.","გრაფიკს ორი კვირით ჩამოვრჩებით."],
  ["asap","ASAP","რაც შეიძლება მალე","Reply ASAP, please.","გთხოვ, რაც შეიძლება მალე მიპასუხე."],
  ["eod","EOD (end of day)","დღის ბოლომდე","Send it by EOD.","დღის ბოლომდე გამოაგზავნე."],
  ["eta","ETA","სავარაუდო დრო","What's the ETA?","რა არის სავარაუდო დრო?"],
  ["tbd","TBD","დასაზუსტებელია","The date is TBD.","თარიღი დასაზუსტებელია."],
  ["fyi","FYI","თქვენს საყურადღებოდ","FYI, the office closes early.","თქვენს საყურადღებოდ, ოფისი ადრე იკეტება."],
  ["out-of-office","Out of office","ოფისში არ ვარ (ავტოპასუხი)","I set my out-of-office reply.","ავტოპასუხი დავაყენე."],
  ["business-trip","Business trip","მივლინება","She's on a business trip.","ის მივლინებაშია."],
  ["commute","Commute","სამსახურში მგზავრობა","My commute is 40 minutes.","სამსახურამდე 40 წუთი მიწევს მგზავრობა."],
  ["workday","Workday","სამუშაო დღე","The workday ends at six.","სამუშაო დღე ექვსზე მთავრდება."],
  ["day-off","Day off","დასვენების დღე","I need a day off Friday.","პარასკევს დასვენების დღე მჭირდება."],
  ["sick-leave","Sick leave","ბიულეტენი","He's on sick leave.","ის ბიულეტენზეა."],
  ["inform","Inform","ინფორმირება","Please inform the team.","გთხოვ გუნდს აცნობე."],
  ["notify","Notify","აცნობება","We'll notify you by email.","იმეილით გაცნობებთ."],
  ["announce","Announce","გამოცხადება","They announced the results.","შედეგები გამოაცხადეს."],
  ["announcement","Announcement","საჯარო განცხადება","Read the announcement.","განცხადება წაიკითხე."],
  ["mention","Mention","ხსენება","He mentioned the budget.","მან ბიუჯეტი ახსენა."],
  ["contact","Contact","კონტაქტი","Contact our support team.","ჩვენს გუნდს დაუკავშირდი."],
  ["apologize","Apologize","ბოდიშის მოხდა","I apologize for the delay.","შეფერხებისთვის ბოდიშს გიხდით."],
  ["appreciate","Appreciate","დაფასება","I appreciate your help.","ვაფასებ შენს დახმარებას."],
  ["handover","Handover","საქმეების გადაბარება","Prepare a handover document.","საქმეების გადასაბარებელი დოკუმენტი მოამზადე."],
  ["wage","Wage","საათობრივი ანაზღაურება","Hourly wage is 15 GEL.","საათობრივი ანაზღაურება 15 ლარია."],
  ["installment","Installment","განვადება","Pay in three installments.","სამი განვადებით გადაიხადე."],
  ["currency","Currency","ვალუტა","Which currency do you accept?","რომელ ვალუტას იღებთ?"],
  ["exchange-rate","Exchange rate","გაცვლითი კურსი","The exchange rate changed.","გაცვლითი კურსი შეიცვალა."],
  ["deposit","Deposit","ავანსი / დეპოზიტი","Pay a 20% deposit.","20%-იანი ავანსი გადაიხადე."],
  ["turnover","Turnover","ბრუნვა","Annual turnover doubled.","წლიური ბრუნვა გაორმაგდა."],
  ["debt","Debt","ვალი","The company has no debt.","კომპანიას ვალი არ აქვს."],
  ["loan","Loan","სესხი","We took a business loan.","ბიზნეს სესხი ავიღეთ."],
  ["interest","Interest","სესხის პროცენტი","The loan interest is high.","სესხის პროცენტი მაღალია."],
  ["purchase","Purchase","ყიდვა","Approve the purchase.","ეს ყიდვა დაამტკიცე."],
  ["order","Order","შეკვეთა","Your order shipped today.","შენი შეკვეთა დღეს გაიგზავნა."],
  ["subscription","Subscription","გამოწერა","Cancel the subscription.","გამოწერა გააუქმე."],
  ["upgrade","Upgrade","აპგრეიდი","Upgrade your plan.","შენი პაკეტი გააუმჯობესე."],
  ["free-trial","Free trial","უფასო საცდელი ვერსია","Start your free trial.","უფასო საცდელი ვერსია დაიწყე."],
  ["complaint","Complaint","საჩივარი","We received a complaint.","საჩივარი მივიღეთ."],
  ["inquiry","Inquiry","ოფიციალური შეკითხვა","We answered the inquiry.","შეკითხვას ვუპასუხეთ."],
  ["satisfaction","Satisfaction","კმაყოფილება","Customer satisfaction improved.","მომხმარებლის კმაყოფილება გაუმჯობესდა."],
  ["loyal","Loyal","ერთგული","Loyal customers return.","ერთგული მომხმარებლები ბრუნდებიან."],
  ["audience","Audience","აუდიტორია","Know your audience.","იცოდე შენი აუდიტორია."],
  ["reliable","Reliable","სანდო","A reliable supplier.","სანდო მომწოდებელი."],
  ["flexible","Flexible","მოქნილი","Flexible working hours.","მოქნილი სამუშაო საათები."],
  ["punctual","Punctual","პუნქტუალური","Be punctual for meetings.","შეხვედრებზე პუნქტუალური იყავი."],
  ["formal","Formal","ოფიციალური","Use a formal tone.","ოფიციალური ტონი გამოიყენე."],
  ["informal","Informal","არაფორმალური","An informal chat.","არაფორმალური საუბარი."],
  ["polite","Polite","თავაზიანი","A polite reply.","თავაზიანი პასუხი."],
  ["concise","Concise","ლაკონური","Keep it concise.","ლაკონურად დაწერე."],
  ["detailed","Detailed","დეტალური","A detailed report.","დეტალური ანგარიში."],
  ["accurate","Accurate","ზუსტი","Accurate numbers matter.","ზუსტი რიცხვები მნიშვნელოვანია."],
  ["efficient","Efficient","ეფექტიანი","An efficient process.","ეფექტიანი პროცესი."],
  ["productive","Productive","პროდუქტიული","A productive meeting.","პროდუქტიული შეხვედრა."],
  ["confident","Confident","თავდაჯერებული","Sound confident.","თავდაჯერებულად ისაუბრე."],
  ["responsible","Responsible","პასუხისმგებელი","She's responsible for sales.","ის გაყიდვებზეა პასუხისმგებელი."],
  ["assign","Assign","დავალების მიცემა","Assign the task to Nika.","ეს დავალება ნიკას მიეცი."],
  ["start","Start","დაწყება","Start the project Monday.","პროექტი ორშაბათს დაიწყე."],
  ["pause","Pause","დაპაუზება","Pause the campaign.","კამპანია დააპაუზე."],
  ["continue","Continue","გაგრძელება","Let's continue tomorrow.","ხვალ გავაგრძელოთ."],
  ["track","Track","თვალყურის დევნება","Track your expenses.","ხარჯებს თვალყური ადევნე."],
  ["measure","Measure","გაზომვა","Measure the results.","შედეგები გაზომე."],
  ["compare","Compare","შედარება","Compare the two offers.","ორი შეთავაზება შეადარე."],
  ["choose","Choose","არჩევა","Choose the best option.","საუკეთესო ვარიანტი აირჩიე."],
  ["avoid","Avoid","თავის არიდება","Avoid long emails.","მოერიდე გრძელ იმეილებს."],
  ["solve","Solve","გადაჭრა / მოგვარება","We solved the problem.","პრობლემა მოვაგვარეთ."],
  ["prepare","Prepare","მომზადება","Prepare the slides.","სლაიდები მოამზადე."],
  ["present","Present","წარდგენა","She'll present the results.","ის შედეგებს წარადგენს."],
  ["organize","Organize","ორგანიზება / დალაგება","Organize the files.","ფაილები დაალაგე."],
  ["arrange","Arrange","მოწყობა","Arrange a call with the client.","კლიენტთან ზარი მოაწყვე."],
  ["handle","Handle","გამკლავება","She handles client emails.","ის კლიენტების იმეილებს უმკლავდება."],
  ["manage","Manage","მართვა","Manage your time well.","დრო კარგად მართე."],
  ["lead-team","Lead (a team)","ხელმძღვანელობა","He leads the design team.","ის დიზაინის გუნდს ხელმძღვანელობს."],
];

// ---- TIER 2: Intermediate (weeks 4-7) ----
const TIER2: Mini[] = [
  ["bandwidth","Bandwidth","რესურსი / დრო","I don't have the bandwidth this week.","ამ კვირას რესურსი არ მაქვს."],
  ["escalate","Escalate","ესკალაცია","Let's escalate this to legal.","ეს იურისტებს გადავცეთ."],
  ["streamline","Streamline","პროცესის გამარტივება","We streamlined the workflow.","სამუშაო პროცესი გავამარტივეთ."],
  ["benchmark","Benchmark","საზომი ნიშნული","Industry benchmarks are clear.","ინდუსტრიული საზომები ცხადია."],
  ["transparency","Transparency","გამჭვირვალობა","We value transparency.","გამჭვირვალობას ვაფასებთ."],
  ["initiative","Initiative","ინიციატივა","Take more initiative.","მეტი ინიციატივა გამოიჩინე."],
  ["collaborate","Collaborate","თანამშრომლობა","We collaborate across teams.","გუნდებს შორის ვთანამშრომლობთ."],
  ["prioritize","Prioritize","პრიორიტეტიზაცია","Prioritize urgent tasks first.","ჯერ გადაუდებელი დავალებები გადაანაწილე."],
  ["delegate","Delegate","დავალების გადაცემა","Learn to delegate.","ისწავლე დელეგირება."],
  ["facilitate","Facilitate","ხელშეწყობა","She facilitated the workshop.","მან ვორქშოპი წარმართა."],
  ["implement","Implement","დანერგვა","Implement the new policy.","ახალი პოლიტიკა დანერგე."],
  ["execute","Execute","შესრულება","We executed the plan well.","გეგმა კარგად შევასრულეთ."],
  ["coordinate","Coordinate","კოორდინაცია","Coordinate with marketing.","მარკეტინგთან კოორდინაცია გააკეთე."],
  ["evaluate","Evaluate","შეფასება","Evaluate the proposal.","წინადადება შეაფასე."],
  ["assess","Assess","სიტუაციის შეფასება","Assess the risk first.","ჯერ რისკი შეაფასე."],
  ["analyze","Analyze","ანალიზი","Analyze the data carefully.","მონაცემები ყურადღებით გააანალიზე."],
  ["forecast","Forecast","პროგნოზი","Forecast next quarter's sales.","შემდეგი კვარტლის გაყიდვები იწინასწარმეტყველე."],
  ["allocate","Allocate","გადანაწილება","Allocate more budget here.","აქ მეტი ბიუჯეტი გადაანაწილე."],
  ["optimize","Optimize","ოპტიმიზაცია","Optimize the process.","პროცესი დახვეწე."],
  ["enhance","Enhance","გაძლიერება / დახვეწა","Enhance customer experience.","მომხმარებლის გამოცდილება გააუმჯობესე."],
  ["improve","Improve","გაუმჯობესება","We improved efficiency.","ეფექტურობა გავაუმჯობესეთ."],
  ["maintain","Maintain","შენარჩუნება / მოვლა","Maintain quality standards.","ხარისხის სტანდარტი შეინარჩუნე."],
  ["sustain","Sustain","მდგრადად შენარჩუნება","We need to sustain growth.","ზრდა უნდა შევინარჩუნოთ."],
  ["scale","Scale","მასშტაბირება","We're ready to scale.","მზად ვართ მასშტაბირებისთვის."],
  ["pivot","Pivot","სტრატეგიის შეცვლა","The startup pivoted.","სტარტაპმა მიმართულება შეცვალა."],
  ["iterate","Iterate","გამეორებითი გაუმჯობესება","Iterate based on feedback.","უკუკავშირზე დაყრდნობით გაიმეორე."],
  ["validate","Validate","ვალიდაცია","Validate the idea first.","ჯერ იდეა დაადასტურე."],
  ["verify","Verify","გადამოწმება","Verify the numbers.","ციფრები გადაამოწმე."],
  ["audit","Audit","აუდიტი","The audit went well.","აუდიტი კარგად ჩატარდა."],
  ["compliance","Compliance","შესაბამისობა","Compliance is mandatory.","შესაბამისობა სავალდებულოა."],
  ["regulation","Regulation","რეგულაცია","New regulations apply.","ახალი რეგულაციები მოქმედებს."],
  ["policy","Policy","პოლიტიკა","Read the company policy.","კომპანიის პოლიტიკა წაიკითხე."],
  ["procedure","Procedure","პროცედურა","Follow the standard procedure.","სტანდარტული პროცედურა დაიცავი."],
  ["protocol","Protocol","პროტოკოლი","There's a protocol for this.","ამისთვის პროტოკოლი არსებობს."],
  ["framework","Framework","ჩარჩო","We use an agile framework.","აგილ ჩარჩოს ვიყენებთ."],
  ["methodology","Methodology","მეთოდოლოგია","Our methodology is solid.","ჩვენი მეთოდოლოგია მყარია."],
  ["approach","Approach","მიდგომა","Try a different approach.","სხვა მიდგომა სცადე."],
  ["strategy","Strategy","სტრატეგია","Our strategy is clear.","სტრატეგია მკაფიოა."],
  ["tactic","Tactic","ტაქტიკა","Change the tactic.","ტაქტიკა შეცვალე."],
  ["objective","Objective","ამოცანა","Define clear objectives.","მკაფიო ამოცანები განსაზღვრე."],
  ["metric","Metric","მეტრიკა","Track these metrics.","ეს მეტრიკები აკონტროლე."],
  ["dashboard","Dashboard","დაშბორდი","Check the dashboard.","დაშბორდი გადახედე."],
  ["funnel","Funnel","ძაბრი (გაყიდვების)","Our funnel is converting.","ჩვენი ძაბრი კარგად მუშაობს."],
  ["conversion","Conversion","კონვერსია","Conversion rate is up.","კონვერსიის მაჩვენებელი გაიზარდა."],
  ["retention","Retention","მომხმარებლის შენარჩუნება","Customer retention matters.","მომხმარებლის შენარჩუნება მნიშვნელოვანია."],
  ["churn","Churn","გადინება","Churn is too high.","გადინება ძალიან მაღალია."],
  ["acquisition","Acquisition","შეძენა","Customer acquisition is costly.","მომხმარებლის შეძენა ძვირია."],
  ["lead","Lead","ლიდი","We got 50 new leads.","50 ახალი ლიდი მივიღეთ."],
  ["prospect","Prospect","პოტენციური კლიენტი","She's a great prospect.","ის კარგი პოტენციური კლიენტია."],
  ["pitch","Pitch","პიჩი / იდეის წარდგენა","I'll pitch tomorrow.","ხვალ წარვადგენ."],
  ["demo","Demo","დემო","Schedule a demo with them.","მათთან დემო დაგეგმე."],
  ["headcount","Headcount","თანამშრომელთა რაოდენობა","Our headcount grew.","თანამშრომელთა რაოდენობა გაიზარდა."],
  ["recruit","Recruit","რეკრუტირება","We're recruiting engineers.","ინჟინრებს ვიყვანთ."],
  ["interview","Interview","გასაუბრება","I have an interview Friday.","პარასკევს გასაუბრება მაქვს."],
  ["candidate","Candidate","კანდიდატი","She's a strong candidate.","ის ძლიერი კანდიდატია."],
  ["promotion","Promotion","დაწინაურება","He got a promotion.","ის დაწინაურდა."],
  ["raise","Raise","ხელფასის მატება","I asked for a raise.","ხელფასის მატება ვითხოვე."],
  ["benefit","Benefit","შეღავათი","Great benefits package.","კარგი შეღავათების პაკეტი."],
  ["bonus","Bonus","ბონუსი","Year-end bonus is coming.","წლის ბოლოს ბონუსი მოდის."],
  ["compensation","Compensation","ანაზღაურება","Compensation is fair.","ანაზღაურება სამართლიანია."],
  ["salary","Salary","ხელფასი","What's the salary range?","რა სახელფასო დიაპაზონია?"],
  ["payroll","Payroll","ხელფასის სია","HR handles payroll.","HR ხელფასებს ამუშავებს."],
  ["resource","Resource","რესურსი","We lack resources.","რესურსები გვაკლია."],
  ["capacity","Capacity","დატვირთვის ზღვარი / სიმძლავრე","Team capacity is full.","გუნდის დატვირთვა ზღვარზეა."],
  ["workload","Workload","დატვირთვა","My workload is heavy.","ჩემი დატვირთვა მძიმეა."],
  ["productivity","Productivity","პროდუქტიულობა","Productivity is rising.","პროდუქტიულობა იზრდება."],
  ["efficiency","Efficiency","ეფექტურობა","Efficiency matters most.","ეფექტურობა ყველაზე მნიშვნელოვანია."],
  ["performance","Performance","შესრულების მაჩვენებელი","Performance review is Monday.","შესრულების შეფასება ორშაბათს."],
  ["evaluation","Evaluation","ფორმალური შეფასება","Annual evaluation is due.","წლიური შეფასების დროა."],
  ["criteria","Criteria","კრიტერიუმი","Define the criteria.","კრიტერიუმები განსაზღვრე."],
  ["standard","Standard","სტანდარტი","Meet the standard.","სტანდარტი დააკმაყოფილე."],
  ["quality","Quality","ხარისხი","Quality over quantity.","ხარისხი რაოდენობაზე მაღლა."],
  ["quantity","Quantity","რაოდენობა","Quantity is fine, quality lacks.","რაოდენობა კარგია, ხარისხი აკლია."],
  ["volume","Volume","მოცულობა","Sales volume increased.","გაყიდვების მოცულობა გაიზარდა."],
  ["throughput","Throughput","გამტარუნარიანობა","Throughput doubled.","გამტარუნარიანობა გაორმაგდა."],
  ["turnaround","Turnaround","შესრულების დრო","Fast turnaround needed.","სწრაფი შესრულება გვჭირდება."],
  ["lead-time","Lead time","მიწოდების დრო","Lead time is two weeks.","მიწოდების დრო ორი კვირაა."],
  ["roadmap","Roadmap","გზამკვლევი","Share the product roadmap.","პროდუქტის გზამკვლევი გააზიარე."],
  ["backlog","Backlog","სამუშაოს რიგი","The backlog is huge.","სამუშაოს რიგი დიდია."],
  ["sprint","Sprint","სპრინტი","Sprint planning is tomorrow.","სპრინტის დაგეგმვა ხვალ არის."],
  ["standup","Standup","სტენდაპი","Standup is at 9 AM.","სტენდაპი დილის 9-ზე."],
  ["retro","Retrospective","რეტროსპექტივა","Retro is Friday.","რეტრო პარასკევს."],
  ["spec","Specification","სპეციფიკაცია","Read the spec carefully.","სპეციფიკაცია ყურადღებით წაიკითხე."],
  ["release","Release","გამოშვება","Release is on Friday.","გამოშვება პარასკევს."],
  ["launch","Launch","გაშვება","Launch went smoothly.","გაშვება შეუფერხებლად ჩაიარა."],
  ["rollout","Rollout","ეტაპობრივი დანერგვა","Phased rollout next week.","ეტაპობრივი გავრცელება მომავალ კვირას."],
  ["adoption","Adoption","ათვისება","User adoption is high.","მომხმარებლის ათვისება მაღალია."],
  ["feedback-loop","Feedback loop","უკუკავშირის ციკლი","Build a feedback loop.","უკუკავშირის ციკლი ააწყვე."],
  ["iteration","Iteration","გამეორება","Each iteration improves.","ყოველი გამეორება აუმჯობესებს."],
  ["proof","Proof of concept","კონცეფციის დადასტურება","Build a quick proof of concept.","სწრაფი კონცეფციის დადასტურება შექმენი."],
  ["mvp","MVP","მინიმალური ვერსია","Ship the MVP first.","ჯერ MVP გაუშვი."],
  ["beta","Beta","ბეტა","We're in beta.","ბეტაში ვართ."],
  ["risk","Risk","რისკი","Identify the risks.","რისკები გამოავლინე."],
  ["mitigation","Mitigation","შერბილება","Risk mitigation plan ready.","რისკის შერბილების გეგმა მზადაა."],
  ["contingency","Contingency","სარეზერვო გეგმა","Have a contingency plan.","სარეზერვო გეგმა გქონდეს."],
  ["dependency","Dependency","დამოკიდებულება","This has a dependency.","ამას დამოკიდებულება აქვს."],
  ["constraint","Constraint","შეზღუდვა","Time is the main constraint.","დრო მთავარი შეზღუდვაა."],
  ["assumption","Assumption","დაშვება","Document your assumptions.","დაშვებები ჩაიწერე."],
  ["hypothesis","Hypothesis","ჰიპოთეზა","Test the hypothesis.","ჰიპოთეზა გადაამოწმე."],
  ["insight","Insight","ინსაითი","Great insight!","კარგი დაკვირვება!"],
  ["data","Data","მონაცემები","Data-driven decisions win.","მონაცემებზე დაფუძნებული გადაწყვეტილებები იმარჯვებს."],
  ["analytics","Analytics","ანალიტიკა","Check the analytics.","ანალიტიკა გადახედე."],
  ["report-out","Report out","ანგარიშგება","Report out at end of week.","კვირის ბოლოს ანგარიში წარადგინე."],
  ["debrief","Debrief","შედეგების განხილვა","Let's debrief after the call.","ზარის შემდეგ განვიხილოთ."],
  ["recap","Recap","მოკლე შეჯამება","Quick recap before we close.","სწრაფი შეჯამება დახურვამდე."],
  ["takeaway","Takeaway","მთავარი დასკვნა","Key takeaway?","მთავარი დასკვნა?"],
  ["action-item","Action item","სამოქმედო პუნქტი","Three action items here.","აქ სამი სამოქმედო პუნქტია."],
  ["next-steps","Next steps","შემდეგი ნაბიჯები","What are the next steps?","რა შემდეგი ნაბიჯებია?"],
  ["touchpoint","Touchpoint","რეგულარული კონტაქტი","Schedule a weekly touchpoint.","ყოველკვირეული შეხვედრა დაგეგმე."],
  ["sync","Sync","სინქრონიზაცია / შეჯერება","Let's sync on Friday.","მოდი პარასკევს შევჯერდეთ."],
  ["check-in","Check-in","მოკლე შეხმიანება","Quick check-in tomorrow.","სწრაფი შემოწმება ხვალ."],
  ["one-on-one","One-on-one","ერთი-ერთზე","I have a 1:1 with my manager.","მენეჯერთან 1:1 მაქვს."],
  ["all-hands","All-hands","საერთო შეხვედრა","All-hands is Thursday.","საერთო შეხვედრა ხუთშაბათს."],
  ["townhall","Townhall","ღია სხდომა","Townhall is on Zoom.","ღია სხდომა Zoom-ში."],
  ["agenda-item","Agenda item","დღის წესრიგის პუნქტი","Add it as an agenda item.","დღის წესრიგში დაამატე."],
  ["minute-taker","Minute-taker","ოქმის წარმოება","Who's the minute-taker?","ვინ აწერს ოქმს?"],
  ["chair","Chair","თავმჯდომარე","She'll chair the meeting.","ის წაუძღვება შეხვედრას."],
  ["consensus","Consensus","კონსენსუსი","Reach consensus first.","ჯერ კონსენსუსამდე მიდი."],
  ["compromise","Compromise","კომპრომისი","Find a compromise.","კომპრომისი იპოვე."],
  ["counteroffer","Counteroffer","საპასუხო შეთავაზება","Send a counteroffer.","საპასუხო შეთავაზება გააგზავნე."],
  ["concession","Concession","დათმობა","Small concession needed.","მცირე დათმობა საჭიროა."],
  ["leverage-point","Leverage point","ბერკეტი","This is a key leverage point.","ეს მნიშვნელოვანი ბერკეტია."],
  ["win-win","Win-win","ორმხრივი მოგება","It's a win-win.","ორმხრივი მოგებაა."],
  ["alignment","Alignment","შეთანხმებულობა","We need alignment first.","ჯერ შეთანხმება გვჭირდება."],
  ["buy-in","Buy-in","მხარდაჭერის მოპოვება","Get leadership buy-in.","ხელმძღვანელობის მხარდაჭერა მიიღე."],
  ["endorsement","Endorsement","ოფიციალური მხარდაჭერა","Their endorsement helps.","მათი მხარდაჭერა გვეხმარება."],
  ["sponsor","Sponsor","სპონსორი","Find an executive sponsor.","აღმასრულებელი სპონსორი იპოვე."],
  ["champion","Champion","იდეის მთავარი მხარდამჭერი","She's our champion.","ის ჩვენი იდეის მთავარი მხარდამჭერია."],
  ["advocate","Advocate","ინტერესების დამცველი","Be a customer advocate.","მომხმარებლის ინტერესების დამცველი იყავი."],
  ["liaison","Liaison","შუამავალი","I'm the liaison.","მე ვარ შუამავალი."],
  ["touchbase","Touch base","დაკავშირება / შეხმიანება","Let's touch base next week.","მოდი მომავალ კვირას დავუკავშირდეთ."],
  ["circle-back","Circle back","დაბრუნება საკითხზე","I'll circle back tomorrow.","ხვალ დავუბრუნდები."],
  ["follow-through","Follow through","ბოლომდე მიყვანა","Follow through on commitments.","ვალდებულებები ბოლომდე მიიყვანე."],
  ["benchmark-set","Benchmarking","შედარებითი ანალიზი","Benchmarking against competitors.","კონკურენტებთან შედარება."],
  ["best-practice","Best practice","საუკეთესო პრაქტიკა","Follow industry best practices.","ინდუსტრიული საუკეთესო პრაქტიკა მიჰყევი."],
  ["case-study","Case study","კეისი","Share the case study.","კეისი გააზიარე."],
  ["white-paper","White paper","თეთრი წიგნი","Download the white paper.","თეთრი წიგნი ჩამოტვირთე."],
  ["press-release","Press release","პრესრელიზი","PR is going out today.","პრესრელიზი დღეს გადის."],
  ["statement","Statement","განცხადება","Read the official statement.","ოფიციალური განცხადება წაიკითხე."],
  ["disclaimer","Disclaimer","გაფრთხილება","Read the disclaimer.","გაფრთხილება წაიკითხე."],
  ["confidential","Confidential","კონფიდენციალური","This is confidential.","ეს კონფიდენციალურია."],
  ["nda","NDA","კონფიდენციალურობის ხელშეკრულება","Please sign the NDA.","გთხოვ NDA-ს მოაწერე ხელი."],
  ["liability","Liability","იურიდიული პასუხისმგებლობა","Limited liability.","შეზღუდული პასუხისმგებლობა."],
  ["warranty","Warranty","გარანტია","One-year warranty.","ერთწლიანი გარანტია."],
  ["clause","Clause","მუხლი","Read this clause carefully.","ეს მუხლი ყურადღებით წაიკითხე."],
  ["agreement","Agreement","შეთანხმება","We have an agreement.","შეთანხმება გვაქვს."],
  ["amendment","Amendment","შესწორება","Sign the amendment.","შესწორებას ხელი მოაწერე."],
  ["addendum","Addendum","დანართი","Add an addendum.","დანართი დაამატე."],
  ["renewal","Renewal","კონტრაქტის განახლება","The contract renewal is up.","კონტრაქტის განახლების დროა."],
  ["termination","Termination","შეწყვეტა","30-day termination notice.","30-დღიანი შეწყვეტის ვადა."],
];

// ---- TIER 3: Advanced (weeks 8-12) ----
const TIER3: Mini[] = [
  ["synergy","Synergy","სინერგია","Cross-team synergy is key.","გუნდთაშორისი სინერგია მთავარია."],
  ["alignment-strategic","Strategic alignment","სტრატეგიული შეთანხმება","Strategic alignment matters.","სტრატეგიული შეთანხმება მნიშვნელოვანია."],
  ["value-prop","Value proposition","ღირებულების შეთავაზება","Sharpen the value proposition.","ღირებულების შეთავაზება გაასწორე."],
  ["due-diligence","Due diligence","საფუძვლიანი შემოწმება","Do your due diligence.","საფუძვლიანი შემოწმება გააკეთე."],
  ["risk-mitigation","Risk mitigation","რისკის შერბილება","Risk mitigation is essential.","რისკის შერბილება აუცილებელია."],
  ["competitive-advantage","Competitive advantage","კონკურენტული უპირატესობა","Find your competitive advantage.","შენი კონკურენტული უპირატესობა იპოვე."],
  ["market-penetration","Market penetration","ბაზრის შეღწევა","Market penetration strategy.","ბაზრის შეღწევის სტრატეგია."],
  ["market-share","Market share","ბაზრის წილი","We gained market share.","ბაზრის წილი მოვიპოვეთ."],
  ["roi","ROI","ინვესტიციის უკუგება","What's the ROI?","რა ROI იქნება?"],
  ["kpi-advanced","KPI","ეფექტურობის საზომი","Track quarterly KPIs.","კვარტალური KPI-ები აკონტროლე."],
  ["merger","Merger","შერწყმა","The merger closed.","შერწყმა დასრულდა."],
  ["acquisition-corp","Acquisition","შეძენა","The acquisition was strategic.","შეძენა სტრატეგიული იყო."],
  ["restructuring","Restructuring","რესტრუქტურიზაცია","Restructuring is underway.","რესტრუქტურიზაცია მიმდინარეობს."],
  ["divestiture","Divestiture","გასხვისება","Divestiture of the division.","ქვედანაყოფის გასხვისება."],
  ["spinoff","Spinoff","გამოყოფა","Plans for a spinoff.","გამოყოფის გეგმები."],
  ["ipo","IPO","საჯარო შეთავაზება","Preparing for IPO.","IPO-სთვის ემზადებიან."],
  ["valuation","Valuation","კომპანიის შეფასება / ვალუაცია","Current valuation is high.","მიმდინარე ვალუაცია მაღალია."],
  ["equity","Equity","კაპიტალი","Equity stake of 10%.","კაპიტალის 10% წილი."],
  ["dilution","Dilution","წილის განზავება","Avoid further dilution.","შემდგომი განზავება აირიდე."],
  ["leverage-fin","Financial leverage","ფინანსური ბერკეტი","Use less leverage.","ნაკლები ბერკეტი გამოიყენე."],
  ["liquidity","Liquidity","ლიკვიდურობა","Maintain liquidity.","ლიკვიდურობა შეინარჩუნე."],
  ["solvency","Solvency","გადახდისუნარიანობა","Solvency is solid.","გადახდისუნარიანობა მყარია."],
  ["cash-flow","Cash flow","ფულის ნაკადი","Cash flow is positive.","ფულის ნაკადი დადებითია."],
  ["working-capital","Working capital","საბრუნავი კაპიტალი","Manage working capital.","საბრუნავი კაპიტალი მართე."],
  ["capex","CAPEX","კაპიტალური ხარჯი","Cut CAPEX this year.","ამ წელს CAPEX შეამცირე."],
  ["opex","OPEX","საოპერაციო ხარჯი","Reduce OPEX.","OPEX შეამცირე."],
  ["ebitda","EBITDA","EBITDA — საოპერაციო მოგება პროცენტებამდე, გადასახადებამდე და ცვეთამდე","EBITDA grew 12%.","EBITDA 12%-ით გაიზარდა."],
  ["margin","Margin","მარჟა","Gross margin improved.","მთლიანი მარჟა გაუმჯობესდა."],
  ["overhead","Overhead","ზედნადები ხარჯი","Cut overhead costs.","ზედნადები ხარჯები შეამცირე."],
  ["amortization","Amortization","ამორტიზაცია","Amortization schedule attached.","ამორტიზაციის გრაფიკი თანდართულია."],
  ["depreciation","Depreciation","ცვეთა","Depreciation hit profits.","ცვეთამ მოგება შეამცირა."],
  ["balance-sheet","Balance sheet","ბალანსი","Strong balance sheet.","ძლიერი ბალანსი."],
  ["income-statement","Income statement","შემოსავლების უწყისი","Review the income statement.","შემოსავლების უწყისი გადახედე."],
  ["p-l","P&L","მოგება-ზარალი","Run the P&L.","მოგება-ზარალი გათვალე."],
  ["forecasting","Forecasting","პროგნოზირება","Improve forecasting accuracy.","პროგნოზირების სიზუსტე გააუმჯობესე."],
  ["variance","Variance","გადახრა","Explain the variance.","გადახრა ახსენი."],
  ["governance","Governance","მმართველობა","Strong governance matters.","ძლიერი მმართველობა მნიშვნელოვანია."],
  ["board","Board","საბჭო","Present to the board.","საბჭოს წინაშე წარადგინე."],
  ["shareholder","Shareholder","აქციონერი","Shareholder meeting Monday.","აქციონერთა შეხვედრა ორშაბათს."],
  ["dividend","Dividend","დივიდენდი","Pay a dividend.","დივიდენდი გადაიხადე."],
  ["share-repurchase","Share buyback","აქციების უკან გამოსყიდვა","Approved share buyback.","აქციების უკან გამოსყიდვა დამტკიცდა."],
  ["esg","ESG","გარემო, სოციალური და მმართველობითი ფაქტორები","ESG goals matter.","ESG მიზნები მნიშვნელოვანია."],
  ["sustainability","Sustainability","მდგრადობა","Sustainability is core.","მდგრადობა მთავარია."],
  ["carbon-footprint","Carbon footprint","ნახშირბადის კვალი","Reduce carbon footprint.","ნახშირბადის კვალი შეამცირე."],
  ["diversity","Diversity","მრავალფეროვნება","Diversity drives innovation.","მრავალფეროვნება ინოვაციას ბადებს."],
  ["inclusion","Inclusion","ჩართვა","Inclusion matters.","ჩართულობა მნიშვნელოვანია."],
  ["equity-dei","Pay equity","ანაზღაურების თანასწორობა","Equity in pay.","ანაზღაურების თანასწორობა."],
  ["empower","Empower","გაძლიერება","Empower your team.","გუნდი გააძლიერე."],
  ["transformation","Transformation","ტრანსფორმაცია","Digital transformation underway.","ციფრული ტრანსფორმაცია მიმდინარეობს."],
  ["disruption","Disruption","ბაზრის ძირეული ცვლილება","Industry disruption is real.","ინდუსტრიის ძირეული ცვლილება რეალურია."],
  ["innovation","Innovation","ინოვაცია","Innovation is key.","ინოვაცია მთავარია."],
  ["incubator","Incubator","ინკუბატორი","Joined a startup incubator.","სტარტაპ ინკუბატორს შევუერთდით."],
  ["accelerator","Accelerator","აქსელერატორი","We're in an accelerator.","აქსელერატორში ვართ."],
  ["seed","Seed funding","სიდ დაფინანსება","Closed seed funding.","სიდ რაუნდი დავხურეთ."],
  ["series-a","Series A","სტარტაპის პირველი ძირითადი საინვესტიციო რაუნდი","Raising a Series A.","Series A ვაგროვებთ."],
  ["runway","Runway","ფინანსური მარაგის ვადა","18 months of runway.","18 თვის ფინანსური მარაგი გვაქვს."],
  ["burn-rate","Burn rate","ხარჯვის სიჩქარე","Burn rate is high.","ხარჯვის სიჩქარე მაღალია."],
  ["unit-economics","Unit economics","ერთეულის ეკონომიკა","Solid unit economics.","მყარი ერთეულის ეკონომიკა."],
  ["cohort","Cohort","კოჰორტი","Cohort analysis shows growth.","კოჰორტული ანალიზი ზრდას აჩვენებს."],
  ["ltv","LTV","მომხმარებლის სიცოცხლის ღირებულება","LTV is improving.","LTV უმჯობესდება."],
  ["cac","CAC","მომხმარებლის შეძენის ღირებულება","Lower CAC is the goal.","CAC-ის შემცირება მიზანია."],
  ["mrr","MRR","ყოველთვიური განმეორებადი შემოსავალი","MRR doubled.","MRR გაორმაგდა."],
  ["arr","ARR","წლიური განმეორებადი შემოსავალი","ARR is $5M.","ARR არის $5M."],
  ["nps","NPS","კლიენტთა ლოიალურობის ინდექსი","NPS jumped to 60.","NPS 60-მდე გაიზარდა."],
  ["csat","CSAT","კლიენტის კმაყოფილების მაჩვენებელი","CSAT improved this month.","CSAT ამ თვეში გაუმჯობესდა."],
  ["sla","SLA","მომსახურების დონის შეთანხმება","Meet the SLA.","SLA დაიცავი."],
  ["slo","SLO","მომსახურების დონის მიზანი","Define clear SLOs.","მკაფიო SLO-ები განსაზღვრე."],
  ["uptime","Uptime","ხელმისაწვდომობა","99.9% uptime.","99.9% ხელმისაწვდომობა."],
  ["downtime","Downtime","გათიშვის დრო","Minimize downtime.","გათიშვის დრო შეამცირე."],
  ["incident","Incident","ინციდენტი","Resolved the incident.","ინციდენტი მოგვარდა."],
  ["postmortem","Postmortem","შემდგომი ანალიზი","Schedule a postmortem.","შემდგომი ანალიზი დაგეგმე."],
  ["root-cause","Root cause","ძირითადი მიზეზი","Find the root cause.","ძირითადი მიზეზი იპოვე."],
  ["technical-debt","Technical debt","ტექნიკური ვალი","Pay down technical debt.","ტექნიკური ვალი დაფარე."],
  ["architecture","Architecture","არქიტექტურა","Review the architecture.","არქიტექტურა გადახედე."],
  ["scalability","Scalability","მასშტაბურობა","Scalability is critical.","მასშტაბურობა კრიტიკულია."],
  ["resilience","Resilience","გამძლეობა","System resilience matters.","სისტემის გამძლეობა მნიშვნელოვანია."],
  ["redundancy","Redundancy","რეზერვირება","Build in redundancy.","რეზერვირება ჩადე."],
  ["latency","Latency","ლატენტურობა","Reduce latency.","ლატენტურობა შეამცირე."],
  ["throughput-tech","Throughput","გამტარუნარიანობა","Increase throughput.","გამტარუნარიანობა გაზარდე."],
  ["bottleneck","Bottleneck","შეფერხების წერტილი","Identify the bottleneck.","შეფერხების წერტილი იპოვე."],
  ["chokepoint","Choke point","კრიტიკული წერტილი","Avoid choke points.","კრიტიკული წერტილები აარიდე."],
  ["capacity-planning","Capacity planning","სიმძლავრის დაგეგმვა","Capacity planning is crucial.","სიმძლავრის დაგეგმვა გადამწყვეტია."],
  ["procurement","Procurement","შესყიდვა","Procurement approved it.","შესყიდვებმა დაამტკიცა."],
  ["sourcing","Sourcing","წყაროების მოძიება","Strategic sourcing matters.","სტრატეგიული წყაროების მოძიება მნიშვნელოვანია."],
  ["supply-chain","Supply chain","მიწოდების ჯაჭვი","Supply chain disruption.","მიწოდების ჯაჭვის შეფერხება."],
  ["logistics","Logistics","ლოგისტიკა","Logistics is complex.","ლოგისტიკა რთულია."],
  ["inventory","Inventory","ინვენტარი","Inventory is low.","ინვენტარი დაბალია."],
  ["warehouse","Warehouse","საწყობი","Warehouse is full.","საწყობი სავსეა."],
  ["fulfillment","Fulfillment","შეკვეთის შესრულება","Fulfillment is fast.","შესრულება სწრაფია."],
  ["distribution","Distribution","გავრცელება / დისტრიბუცია","Distribution expanded.","გავრცელება გაფართოვდა."],
  ["channel","Channel","არხი","New sales channel.","ახალი გაყიდვების არხი."],
  ["b2b","B2B","ბიზნესი-ბიზნესს","We're B2B focused.","B2B-ზე ფოკუსირებული ვართ."],
  ["b2c","B2C","ბიზნესი-მომხმარებელს","B2C is competitive.","B2C კონკურენტულია."],
  ["segment","Segment","სეგმენტი","Segment your audience.","აუდიტორია სეგმენტებად დაყავი."],
  ["positioning","Positioning","პოზიციონირება","Sharpen positioning.","პოზიციონირება გაასწორე."],
  ["differentiation","Differentiation","დიფერენციაცია","Differentiation matters.","დიფერენციაცია მნიშვნელოვანია."],
  ["brand-equity","Brand equity","ბრენდის ღირებულება","Brand equity grew.","ბრენდის ღირებულება გაიზარდა."],
  ["brand-awareness","Brand awareness","ბრენდის ცნობადობა","Boost brand awareness.","ბრენდის ცნობადობა გაზარდე."],
  ["thought-leadership","Thought leadership","აზრის ლიდერობა","Build thought leadership.","აზრის ლიდერობა გამოაქცე."],
  ["go-to-market","Go-to-market","ბაზარზე გასვლა","Solid go-to-market plan.","მყარი GTM გეგმა."],
  ["product-market-fit","Product-market fit","პროდუქტ-ბაზრის შესაბამისობა","Reach product-market fit.","პროდუქტ-ბაზრის შესაბამისობას მიაღწიე."],
  ["customer-success","Customer success","მომხმარებლის წარმატება","Invest in customer success.","მომხმარებლის წარმატებაში ჩადე."],
  ["customer-journey","Customer journey","მომხმარებლის გზა","Map the customer journey.","მომხმარებლის გზა გაშალე."],
  ["ux","UX","მომხმარებლის გამოცდილება","Improve UX.","UX გააუმჯობესე."],
  ["ui","UI","მომხმარებლის ინტერფეისი","Polish the UI.","UI გაასწორე."],
  ["wireframe","Wireframe","ვაირფრეიმი","Share the wireframe.","ვაირფრეიმი გააზიარე."],
  ["prototype","Prototype","პროტოტიპი","Build a prototype.","პროტოტიპი ააწყვე."],
  ["mockup","Mockup","მაკეტი","Approve the mockup.","მაკეტი დაამტკიცე."],
  ["a-b-test","A/B test","A/B ტესტი","Run an A/B test.","A/B ტესტი ჩაატარე."],
  ["experiment","Experiment","ექსპერიმენტი","Design an experiment.","ექსპერიმენტი დაგეგმე."],
  ["significance","Significance","მნიშვნელოვნება","Statistical significance.","სტატისტიკური მნიშვნელოვნება."],
  ["sample-size","Sample size","ნიმუშის ზომა","Sample size is small.","ნიმუშის ზომა მცირეა."],
  ["bias","Bias","მიკერძოება","Watch out for bias.","მიკერძოებას უფრთხილდი."],
  ["correlation","Correlation","კორელაცია","Correlation isn't causation.","კორელაცია მიზეზ-შედეგი არ არის."],
  ["causation","Causation","მიზეზობრიობა","Prove causation.","მიზეზობრიობა დაამტკიცე."],
  ["regression","Regression","რეგრესია","Run a regression.","რეგრესია გაუშვი."],
  ["forecast-model","Forecast model","პროგნოზის მოდელი","Build a forecast model.","პროგნოზის მოდელი შექმენი."],
  ["scenario","Scenario","სცენარი","Model three scenarios.","სამი სცენარი დაამოდელირე."],
  ["sensitivity","Sensitivity","მგრძნობელობა","Sensitivity analysis next.","შემდეგ მგრძნობელობის ანალიზი."],
  ["paradigm","Paradigm","პარადიგმა","Paradigm shift happening.","პარადიგმის ცვლილებაა."],
  ["disruption-adv","Disruptor","ბაზრის შემცვლელი მოთამაშე","They're a market disruptor.","ისინი ბაზრის შემცვლელი მოთამაშეები არიან."],
  ["incumbent","Incumbent","მოქმედი მოთამაშე","Incumbents are slow.","მოქმედი მოთამაშეები ნელია."],
  ["entrant","New entrant","ახალი მოთამაშე","New entrant in the market.","ბაზარზე ახალი მოთამაშე."],
  ["moat","Moat","კონკურენტული ბარიერი","Build a strong moat.","ძლიერი ბარიერი ააწყვე."],
  ["network-effect","Network effect","ქსელის ეფექტი","Strong network effects.","ძლიერი ქსელის ეფექტი."],
  ["flywheel","Flywheel","ფლაივილი","Build the flywheel.","ფლაივილი ააწყვე."],
  ["adoption-curve","Adoption curve","ათვისების მრუდი","Crossing the adoption curve.","ათვისების მრუდის გადალახვა."],
  ["chasm","Chasm","ნაპრალი","Cross the chasm.","ნაპრალი გადალახე."],
  ["early-adopter","Early adopter","ადრეული მომხმარებელი","Target early adopters.","ადრეულ მომხმარებლებზე ფოკუსირდი."],
  ["laggard","Laggard","გვიანი მომხმარებელი","Laggards convert last.","გვიანი მომხმარებლები ბოლოს კონვერტირდებიან."],
];

// Spread indices evenly across a week range so words never overflow their
// intended tier (the old `Math.floor(i / 35)` pushed late TIER1 words into
// week 4 → misclassified as tier 2, and late TIER2 words into tier 3).
const spreadWeek = (i: number, len: number, start: number, end: number) =>
  start + Math.min(end - start, Math.floor((i * (end - start + 1)) / Math.max(1, len)));

const CORE_EXTRA: VocabWord[] = [
  ...TIER1.map((m, i) => mk(m, spreadWeek(i, TIER1.length, 1, 3))),   // weeks 1-3
  ...TIER2.map((m, i) => mk(m, spreadWeek(i, TIER2.length, 4, 7))),   // weeks 4-7
  ...TIER3.map((m, i) => mk(m, spreadWeek(i, TIER3.length, 8, 12))),  // weeks 8-12
];

// ---- TIER 4: Field-specific (mapped to BusinessField/goals) ----
const FIELD_EXTRA: VocabWord[] = [
  // remote / freelance
  ...([
    ["scope-creep","Scope creep","სამუშაოს ფარგლების უკონტროლო ზრდა","Watch out for scope creep.","სამუშაოს ზრდას უფრთხილდი."],
    ["portfolio","Portfolio","პორტფოლიო","Share your portfolio.","შენი პორტფოლიო გააზიარე."],
    ["freelance","Freelance","ფრილანსერი","I freelance on the side.","დამატებით ფრილანსად ვმუშაობ."],
    ["asynchronous","Asynchronous","ასინქრონული","Async work is normal here.","ასინქრონული მუშაობა აქ ნორმაა."],
    ["timezone","Time zone","დროის სარტყელი","We're in different time zones.","სხვადასხვა დროის სარტყელში ვართ."],
    ["co-working","Co-working","კოვორქინგი","Co-working space downtown.","ცენტრში კოვორქინგი."],
    ["nomad","Digital nomad","ციფრული მომთაბარე","She's a digital nomad.","ის ციფრული მომთაბარეა."],
    ["retainer-fee","Retainer fee","ფიქსირებული საფასური","Monthly retainer fee.","ყოველთვიური ფიქსირებული საფასური."],
    ["statement-of-work","Statement of work","სამუშაოს აღწერა","Sign the SOW.","SOW-ს ხელი მოაწერე."],
    ["milestone-payment","Milestone payment","ეტაპობრივი გადახდა","Milestone payment cleared.","ეტაპობრივი გადახდა ჩაჯდა."],
  ] as Mini[]).map((m) => mkField(m, "remote_work")),
  // management
  ...([
    ["performance-review","Performance review","საქმიანობის შეფასება","Performance review next week.","საქმიანობის შეფასება მომავალ კვირას."],
    ["org-chart","Org chart","ორგანიზაციული სქემა","Update the org chart.","ორგანიზაციული სქემა განაახლე."],
    ["headcount-plan","Headcount plan","საშტატო გეგმა","Submit headcount plan.","საშტატო გეგმა წარადგინე."],
    ["span-of-control","Span of control","კონტროლის დიაპაზონი","Wider span of control.","კონტროლის უფრო ფართო დიაპაზონი."],
    ["succession","Succession planning","შემცვლელის დაგეგმვა","Succession planning matters.","შემცვლელის დაგეგმვა მნიშვნელოვანია."],
    ["one-on-one-mgmt","1:1","ერთი-ერთზე შეხვედრა","Weekly 1:1 with each report.","ყოველკვირეული 1:1 თითოეულთან."],
    ["okr","OKR","მიზნები და ძირითადი შედეგები","Set quarterly OKRs.","კვარტალური OKR-ები დააწესე."],
    ["leadership","Leadership","ლიდერობა","Good leadership builds trust.","კარგი ლიდერობა ნდობას აშენებს."],
    ["culture","Culture","კულტურა","Culture eats strategy.","კულტურა სტრატეგიაზე ძლიერია."],
    ["psychological-safety","Psychological safety","ფსიქოლოგიური უსაფრთხოება","Build psychological safety.","ფსიქოლოგიური უსაფრთხოება შექმენი."],
  ] as Mini[]).map((m) => mkField(m, "management")),
  // marketing
  ...([
    ["ctr","CTR","დაწკაპუნების კოეფიციენტი","Our CTR is up 5% this week.","ჩვენი CTR 5%-ით გაიზარდა ამ კვირაში."],
    ["cpc","CPC","ღირებულება ერთ დაწკაპუნებაზე","Lower CPC is the goal.","CPC-ის შემცირება მიზანია."],
    ["cpm","CPM","ღირებულება ათას ჩვენებაზე","Negotiate CPM down.","CPM ჩამოშალე."],
    ["sem","SEM","ძიების სისტემაში მარკეტინგი","SEM budget approved.","SEM ბიუჯეტი დამტკიცდა."],
    ["seo","SEO","ძიების სისტემისთვის ოპტიმიზაცია","SEO drives organic traffic.","SEO ორგანულ ტრაფიკს იძლევა."],
    ["organic","Organic","ორგანული","Organic reach declined.","ორგანული წვდომა შემცირდა."],
    ["paid","Paid media","ფასიანი მედია","Paid media is scaling.","ფასიანი მედია მასშტაბირდება."],
    ["impression","Impression","ჩვენება","Impressions grew 20%.","ჩვენებები 20%-ით გაიზარდა."],
    ["reach","Reach","მოცვა / წვდომა","Reach expanded.","აუდიტორიის მოცვა გაფართოვდა."],
    ["engagement-rate","Engagement rate","ჩართულობის მაჩვენებელი","High engagement rate.","მაღალი ჩართულობის მაჩვენებელი."],
    ["funnel-mk","Marketing funnel","მარკეტინგული ძაბრი","Top-of-funnel content.","ძაბრის ზედა კონტენტი."],
    ["lead-gen","Lead generation","ლიდის გენერაცია","Lead generation is up.","ლიდის გენერაცია გაიზარდა."],
    ["nurture","Nurture","ლიდების მოვლა-განვითარება","Nurture leads with email.","ლიდები იმეილით განავითარე."],
    ["personalization","Personalization","პერსონალიზაცია","Personalization boosts results.","პერსონალიზაცია შედეგებს ზრდის."],
    ["attribution","Attribution","ატრიბუცია","Multi-touch attribution.","მრავალწერტილოვანი ატრიბუცია."],
  ] as Mini[]).map((m) => mkField(m, "marketing")),
  // sales
  ...([
    ["quota","Quota","კვოტა","Hit the quota.","კვოტა შეასრულე."],
    ["commission","Commission","საკომისიო","Commission is 10%.","საკომისიო 10%-ია."],
    ["close-rate","Close rate","გარიგების დახურვის %","Close rate improved.","გარიგების დახურვის % გაუმჯობესდა."],
    ["upsell","Upsell","დამატებითი გაყიდვა","Upsell to existing clients.","არსებულ კლიენტებს უფრო მაღალი პაკეტი შესთავაზე."],
    ["cross-sell","Cross-sell","კროს-გაყიდვა","Cross-sell opportunities.","კროს-გაყიდვის შესაძლებლობები."],
    ["discovery-call","Discovery call","გაცნობითი ზარი","Schedule a discovery call.","გაცნობითი ზარი დაგეგმე."],
    ["qualified-lead","Qualified lead","კვალიფიცირებული ლიდი","Qualified leads only.","მხოლოდ კვალიფიცირებული ლიდები."],
    ["closing","Closing","გარიგების დახურვა","Closing is an art.","გარიგების დახურვა ხელოვნებაა."],
    ["objection","Objection","წინააღმდეგობა","Handle objections well.","წინააღმდეგობებს კარგად გაუმკლავდი."],
  ] as Mini[]).map((m) => mkField(m, "sales")),
  // finance / accounting / economics
  ...([
    ["ledger","Ledger","ჟურნალი","Update the ledger.","ჟურნალი განაახლე."],
    ["reconcile","Reconcile","შეჯერება","Reconcile the accounts.","ანგარიშები შეაჯერე."],
    ["accrual","Accrual","დარიცხვა","Accrual accounting basics.","დარიცხვითი აღრიცხვის საფუძვლები."],
    ["receivables","Receivables","დებიტორული დავალიანება","Manage receivables.","დებიტორული დავალიანება მართე."],
    ["payables","Payables","კრედიტორული დავალიანება","Pay the payables on time.","კრედიტორული დავალიანება დროულად დაფარე."],
    ["audit-fin","Audit","აუდიტი","Annual audit complete.","წლიური აუდიტი დასრულდა."],
    ["compliance-fin","Compliance","შესაბამისობა","Financial compliance.","ფინანსური შესაბამისობა."],
    ["tax","Tax","გადასახადი","Pay taxes quarterly.","გადასახადები კვარტალურად გადაიხადე."],
    ["vat","VAT","დღგ","VAT applies here.","აქ დღგ ვრცელდება."],
    ["inflation","Inflation","ინფლაცია","Inflation is rising.","ინფლაცია იზრდება."],
    ["interest-rate","Interest rate","საპროცენტო განაკვეთი","Interest rates dropped.","საპროცენტო განაკვეთები დაეცა."],
    ["recession","Recession","რეცესია","Recession is possible.","რეცესია შესაძლებელია."],
    ["gdp","GDP","მშპ","GDP grew 3%.","მშპ 3%-ით გაიზარდა."],
    ["supply-demand","Supply and demand","მიწოდება-მოთხოვნა","Supply and demand basics.","მიწოდება-მოთხოვნის საფუძვლები."],
    ["monetary-policy","Monetary policy","მონეტარული პოლიტიკა","Monetary policy tightened.","მონეტარული პოლიტიკა გამკაცრდა."],
  ] as Mini[]).map((m) => mkField(m, "finance")),
  // HR
  ...([
    ["recruitment","Recruitment","რეკრუტინგი","Recruitment is active.","რეკრუტინგი აქტიურია."],
    ["job-description","Job description","ვაკანსიის აღწერა","Update the job description.","ვაკანსიის აღწერა განაახლე."],
    ["screening","Screening","გადარჩევა","Resume screening first.","ჯერ რეზიუმეების გადარჩევა."],
    ["offer-letter","Offer letter","შემოთავაზების წერილი","Send the offer letter.","შემოთავაზების წერილი გააგზავნე."],
    ["benefits-hr","Benefits","შეღავათები","Benefits enrollment open.","შეღავათების რეგისტრაცია ღიაა."],
    ["pto","PTO","ფასიანი შვებულება","PTO request approved.","PTO მოთხოვნა დამტკიცდა."],
    ["termination-hr","Termination","შეწყვეტა","Termination process.","შეწყვეტის პროცესი."],
    ["exit-interview","Exit interview","გასვლის ინტერვიუ","Conduct exit interviews.","გასვლის ინტერვიუ ჩაატარე."],
    ["engagement-hr","Employee engagement","თანამშრომელთა ჩართულობა","Employee engagement survey.","თანამშრომელთა ჩართულობის გამოკითხვა."],
    ["retention-hr","Retention","თანამშრომელთა შენარჩუნება","Improve retention.","შენარჩუნება გააუმჯობესე."],
  ] as Mini[]).map((m) => mkField(m, "hr")),
  // project management
  ...([
    ["gantt","Gantt chart","განტის გრაფიკი","Show me the Gantt chart.","განტის გრაფიკი მაჩვენე."],
    ["critical-path","Critical path","კრიტიკული გზა","Identify the critical path.","კრიტიკული გზა იპოვე."],
    ["resource-allocation","Resource allocation","რესურსის გადანაწილება","Improve resource allocation.","რესურსის გადანაწილება გააუმჯობესე."],
    ["risk-register","Risk register","რისკის რეესტრი","Update the risk register.","რისკის რეესტრი განაახლე."],
    ["change-request","Change request","ცვლილების მოთხოვნა","Submit a change request.","ცვლილების მოთხოვნა წარადგინე."],
    ["pmo","PMO","პროექტების მართვის ოფისი","PMO oversees projects.","PMO ზედამხედველობს პროექტებს."],
    ["pm","Project manager","პროექტის მენეჯერი","She's our PM.","ის ჩვენი PM-ია."],
    ["agile","Agile","Agile მეთოდი","We work Agile.","Agile მეთოდით ვმუშაობთ."],
    ["scrum","Scrum","სქრამი","Scrum ceremonies daily.","სქრამის რიტუალები ყოველდღე."],
    ["kanban","Kanban","კანბანი","Kanban board updated.","კანბანის დაფა განახლდა."],
  ] as Mini[]).map((m) => mkField(m, "project_management")),
];

// Map BusinessField + priorities to keys to fetch the right field words.
export function fieldKeysFor(fields: string[] = [], goals: string[] = []): string[] {
  const keys = new Set<string>();
  fields.forEach((f) => keys.add(f));
  if (goals.includes("remote_work")) keys.add("remote_work");
  if (goals.includes("emails_writing")) keys.add("remote_work");
  return Array.from(keys);
}

const ALL_FIELD_WORDS = [...FIELD_WORDS, ...FIELD_EXTRA];

export function fieldWordsFor(fields: string[] = [], goals: string[] = []): VocabWord[] {
  const keys = fieldKeysFor(fields, goals);
  if (!keys.length) return [];
  return ALL_FIELD_WORDS.filter((w) => w.field && keys.includes(w.field));
}

export const ALL_WORDS: VocabWord[] = [...CORE_WORDS, ...CORE_EXTRA, ...ALL_FIELD_WORDS];
export const ALL_CORE_WORDS: VocabWord[] = [...CORE_WORDS, ...CORE_EXTRA];

export function findWord(key: string): VocabWord | undefined {
  return ALL_WORDS.find((w) => w.key === key);
}

// ---------------- COMMON GEORGIAN MISTAKES ----------------

export type GeorgianMistake = {
  key: string;
  wrong: string;
  right: string;
  explanationKa: string;
  level: 1 | 2 | 3;
};

export const GEORGIAN_MISTAKES: GeorgianMistake[] = [
  {
    key: "interested",
    wrong: "I am interesting in marketing.",
    right: "I am interested in marketing.",
    explanationKa: "'Interesting' = საინტერესო (საგანი). შენ ხარ 'interested' — დაინტერესებული.",
    level: 1,
  },
  {
    key: "age",
    wrong: "I have 25 years.",
    right: "I am 25 years old.",
    explanationKa: "ინგლისურში ასაკზე ვამბობთ 'I am X years old', არა 'I have'.",
    level: 1,
  },
  {
    key: "turn-on",
    wrong: "Please open the light.",
    right: "Please turn on the light.",
    explanationKa: "სინათლე და მოწყობილობები 'turn on/off' — არა 'open/close'.",
    level: 1,
  },
  {
    key: "depend-on",
    wrong: "It depends from the team.",
    right: "It depends on the team.",
    explanationKa: "'Depend' ყოველთვის თხოულობს 'on'-ს, არა 'from'-ს.",
    level: 2,
  },
  {
    key: "listen-to",
    wrong: "I listen the manager carefully.",
    right: "I listen to the manager carefully.",
    explanationKa: "'Listen' ყოველთვის გვჭირდება 'to'-სთან ერთად.",
    level: 2,
  },
  {
    key: "look-forward",
    wrong: "I look forward to hear from you.",
    right: "I look forward to hearing from you.",
    explanationKa: "'Look forward to'-ის შემდეგ ზმნა -ing ფორმაში დგას.",
    level: 2,
  },
  {
    key: "make-vs-do",
    wrong: "I will do a presentation tomorrow.",
    right: "I will give a presentation tomorrow.",
    explanationKa: "პრეზენტაციას 'give' ვაკეთებთ ინგლისურში, არა 'do'.",
    level: 3,
  },
  {
    key: "since-for",
    wrong: "I work here since 3 years.",
    right: "I have worked here for 3 years.",
    explanationKa: "ხანგრძლივობისთვის — 'for' + present perfect. 'Since' კონკრეტული მომენტისთვის (since 2021).",
    level: 3,
  },
  {
    key: "good-at",
    wrong: "She is good in negotiation.",
    right: "She is good at negotiation.",
    explanationKa: "'Good at' — სტანდარტული ფორმა. 'In' აქ არ ჯდება.",
    level: 2,
  },
  {
    key: "advice",
    wrong: "Can you give me some advices?",
    right: "Can you give me some advice?",
    explanationKa: "'Advice' განუთვლადია — მრავლობით რიცხვი არ აქვს.",
    level: 3,
  },
];