// Static Business English vocabulary bank.
// Each word is keyed so progress can be tracked in Supabase by word_key.

export type VocabWord = {
  key: string;            // stable kebab-case id
  en: string;
  ka: string;
  explanationKa: string;
  pronunciation: string;  // simple ka phonetic guide
  exampleEn: string;
  exampleKa: string;
  example2En: string;
  example2Ka: string;
  source: "core" | "field";
  week?: number;          // for core words only
  field?: string;         // for field words
};

// ---------------- CORE CURRICULUM ----------------
// Week 1 foundational → Week 4 advanced. ~6-7 words per week.

export const CORE_WORDS: VocabWord[] = [
  // ---------- WEEK 1: foundations ----------
  {
    key: "deadline",
    en: "Deadline",
    ka: "ბოლო ვადა",
    explanationKa: "ბოლო თარიღი, რომელშიც დავალება უნდა დასრულდეს.",
    pronunciation: "დედლაინ",
    exampleEn: "We need to meet the deadline by Friday.",
    exampleKa: "პარასკევისთვის ვადა უნდა დავიცვათ.",
    example2En: "The deadline has been extended by one week.",
    example2Ka: "ვადა ერთი კვირით გადაიდო.",
    source: "core",
    week: 1,
  },
  {
    key: "client",
    en: "Client",
    ka: "კლიენტი",
    explanationKa: "ადამიანი ან კომპანია, რომელიც იყენებს თქვენს მომსახურებას.",
    pronunciation: "ქლაიენთ",
    exampleEn: "Our biggest client is based in Berlin.",
    exampleKa: "ჩვენი ყველაზე დიდი კლიენტი ბერლინშია.",
    example2En: "I have a call with the client at 3 PM.",
    example2Ka: "15:00-ზე ზარი მაქვს კლიენტთან.",
    source: "core",
    week: 1,
  },
  {
    key: "agenda",
    en: "Agenda",
    ka: "დღის წესრიგი",
    explanationKa: "შეხვედრის ან დღის გეგმა — რა საკითხები განიხილება.",
    pronunciation: "აჯენდა",
    exampleEn: "Let's stick to the agenda.",
    exampleKa: "მოდი დღის წესრიგს მივყვეთ.",
    example2En: "I'll send the agenda before the meeting.",
    example2Ka: "შეხვედრამდე დღის წესრიგს გამოვაგზავნი.",
    source: "core",
    week: 1,
  },
  {
    key: "feedback",
    en: "Feedback",
    ka: "უკუკავშირი",
    explanationKa: "მოსაზრება ან კომენტარი ვინმეს მუშაობაზე.",
    pronunciation: "ფიდბექ",
    exampleEn: "Thanks for the honest feedback on my report.",
    exampleKa: "გმადლობთ ჩემს ანგარიშზე გულახდილი უკუკავშირისთვის.",
    example2En: "I'd appreciate your feedback by tomorrow.",
    example2Ka: "თქვენი უკუკავშირი ხვალამდე მინდა.",
    source: "core",
    week: 1,
  },
  {
    key: "follow-up",
    en: "Follow up",
    ka: "გადამოწმება / დაკავშირება",
    explanationKa: "ხელახლა დაკავშირება საკითხის სტატუსის შესამოწმებლად.",
    pronunciation: "ფოლოუ აპ",
    exampleEn: "I'll follow up with the client next week.",
    exampleKa: "მომავალ კვირას კლიენტს დავუკავშირდები.",
    example2En: "Just following up on my previous email.",
    example2Ka: "უბრალოდ ვამოწმებ ჩემს წინა იმეილს.",
    source: "core",
    week: 1,
  },
  {
    key: "schedule",
    en: "Schedule",
    ka: "გრაფიკი / დანიშვნა",
    explanationKa: "დროის გეგმა; ან ზმნა — დროის დანიშვნა.",
    pronunciation: "სქედჯულ",
    exampleEn: "Can we schedule a call for tomorrow?",
    exampleKa: "შეგვიძლია ხვალისთვის ზარი დავნიშნოთ?",
    example2En: "My schedule is tight this week.",
    example2Ka: "ამ კვირას გრაფიკი დატვირთული მაქვს.",
    source: "core",
    week: 1,
  },
  // ---------- WEEK 2: communication ----------
  {
    key: "stakeholder",
    en: "Stakeholder",
    ka: "დაინტერესებული მხარე",
    explanationKa: "ადამიანი ან ჯგუფი, რომელსაც აქვს ინტერესი პროექტში.",
    pronunciation: "სტეიქჰოლდერ",
    exampleEn: "We need to update all stakeholders weekly.",
    exampleKa: "კვირაში ერთხელ ყველა დაინტერესებულ მხარეს ვაცნობებთ.",
    example2En: "Key stakeholders approved the plan.",
    example2Ka: "ძირითადმა დაინტერესებულმა მხარეებმა გეგმა დაამტკიცეს.",
    source: "core",
    week: 2,
  },
  {
    key: "proposal",
    en: "Proposal",
    ka: "წინადადება",
    explanationKa: "ოფიციალური დოკუმენტი ან იდეა განსახილველად.",
    pronunciation: "პროპოუზალ",
    exampleEn: "I sent the proposal yesterday — let me know your thoughts.",
    exampleKa: "გუშინ წინადადება გამოვაგზავნე — შენი აზრი მაცნობე.",
    example2En: "The client accepted our proposal.",
    example2Ka: "კლიენტმა ჩვენი წინადადება მიიღო.",
    source: "core",
    week: 2,
  },
  {
    key: "revenue",
    en: "Revenue",
    ka: "შემოსავალი",
    explanationKa: "ფული, რომელსაც კომპანია იღებს გაყიდვებიდან.",
    pronunciation: "რევენიუ",
    exampleEn: "Revenue grew by 15% last quarter.",
    exampleKa: "შემოსავალი წინა კვარტალში 15%-ით გაიზარდა.",
    example2En: "We need to increase revenue.",
    example2Ka: "შემოსავალი უნდა გავზარდოთ.",
    source: "core",
    week: 2,
  },
  {
    key: "invoice",
    en: "Invoice",
    ka: "ანგარიშფაქტურა",
    explanationKa: "დოკუმენტი, რომელშიც ჩაწერილია გადასახდელი თანხა მომსახურებისთვის.",
    pronunciation: "ინვოის",
    exampleEn: "I'll send the invoice at the end of the month.",
    exampleKa: "ანგარიშფაქტურას თვის ბოლოს გამოვაგზავნი.",
    example2En: "Please pay the invoice within 14 days.",
    example2Ka: "გთხოვთ ანგარიში 14 დღეში გადაიხადოთ.",
    source: "core",
    week: 2,
  },
  {
    key: "deliver",
    en: "Deliver",
    ka: "ჩაბარება / შესრულება",
    explanationKa: "შეთანხმებული შედეგის ან პროდუქტის დროულად მიწოდება.",
    pronunciation: "დელივერ",
    exampleEn: "We always deliver on time.",
    exampleKa: "ჩვენ ყოველთვის ვაბარებთ დროზე.",
    example2En: "The team delivered great results.",
    example2Ka: "გუნდმა შესანიშნავი შედეგი მოიტანა.",
    source: "core",
    week: 2,
  },
  {
    key: "negotiate",
    en: "Negotiate",
    ka: "მოლაპარაკება",
    explanationKa: "შეთანხმებაზე მისვლა — განხილვა და კომპრომისი.",
    pronunciation: "ნეგოშიეით",
    exampleEn: "Let's negotiate the price next week.",
    exampleKa: "მომავალ კვირას ფასი მოვილაპარაკოთ.",
    example2En: "She negotiated a better contract.",
    example2Ka: "მან უკეთესი კონტრაქტი მოილაპარაკა.",
    source: "core",
    week: 2,
  },
  // ---------- WEEK 3: collaboration ----------
  {
    key: "presentation",
    en: "Presentation",
    ka: "პრეზენტაცია",
    explanationKa: "ფორმალური წარდგენა აუდიტორიის წინაშე.",
    pronunciation: "პრეზენტეიშენ",
    exampleEn: "My presentation is on Friday morning.",
    exampleKa: "ჩემი პრეზენტაცია პარასკევს დილით არის.",
    example2En: "Her presentation was clear and engaging.",
    example2Ka: "მისი პრეზენტაცია ნათელი და საინტერესო იყო.",
    source: "core",
    week: 3,
  },
  {
    key: "approve",
    en: "Approve",
    ka: "დამტკიცება",
    explanationKa: "ოფიციალური თანხმობის გაცემა რაიმეზე.",
    pronunciation: "ეფრუვ",
    exampleEn: "The manager approved the budget.",
    exampleKa: "მენეჯერმა ბიუჯეტი დაამტკიცა.",
    example2En: "Please approve the document by EOD.",
    example2Ka: "გთხოვთ დოკუმენტი დღის ბოლომდე დაამტკიცოთ.",
    source: "core",
    week: 3,
  },
  {
    key: "milestone",
    en: "Milestone",
    ka: "ეტაპი / ნიშნული",
    explanationKa: "მნიშვნელოვანი მიღწევა პროექტში.",
    pronunciation: "მაილსტოუნ",
    exampleEn: "We hit our first milestone last week.",
    exampleKa: "გასულ კვირას პირველ ეტაპს მივაღწიეთ.",
    example2En: "There are three milestones in this project.",
    example2Ka: "ამ პროექტში სამი ეტაპია.",
    source: "core",
    week: 3,
  },
  {
    key: "priority",
    en: "Priority",
    ka: "პრიორიტეტი",
    explanationKa: "ის, რაც სხვაზე უფრო მნიშვნელოვანი ან გადაუდებელია.",
    pronunciation: "პრაიორიტი",
    exampleEn: "This task is our top priority.",
    exampleKa: "ეს დავალება ჩვენი მთავარი პრიორიტეტია.",
    example2En: "Let's set clear priorities for the week.",
    example2Ka: "მოდი კვირის ნათელი პრიორიტეტები დავსახოთ.",
    source: "core",
    week: 3,
  },
  {
    key: "reschedule",
    en: "Reschedule",
    ka: "თარიღის შეცვლა",
    explanationKa: "უკვე დანიშნული შეხვედრის სხვა დროზე გადატანა.",
    pronunciation: "რისქედჯულ",
    exampleEn: "Can we reschedule for Thursday?",
    exampleKa: "შეგვიძლია ხუთშაბათისთვის გადავიტანოთ?",
    example2En: "I had to reschedule the meeting.",
    example2Ka: "შეხვედრის გადატანა მომიწია.",
    source: "core",
    week: 3,
  },
  {
    key: "summary",
    en: "Summary",
    ka: "შეჯამება",
    explanationKa: "მოკლე მიმოხილვა მნიშვნელოვანი ინფორმაციისა.",
    pronunciation: "სამარი",
    exampleEn: "Here's a quick summary of the meeting.",
    exampleKa: "აი შეხვედრის სწრაფი შეჯამება.",
    example2En: "I'll send a summary by email.",
    example2Ka: "შეჯამებას იმეილით გამოვაგზავნი.",
    source: "core",
    week: 3,
  },
  // ---------- WEEK 4: nuance ----------
  {
    key: "leverage",
    en: "Leverage",
    ka: "გამოყენება / ბერკეტი",
    explanationKa: "რესურსის ან უპირატესობის ეფექტურად გამოყენება.",
    pronunciation: "ლევერიჯ",
    exampleEn: "We can leverage our network to find clients.",
    exampleKa: "კლიენტების მოსაძებნად ჩვენი კონტაქტები შეგვიძლია გამოვიყენოთ.",
    example2En: "Leverage your strengths in the interview.",
    example2Ka: "გასაუბრებაზე ძლიერი მხარეები გამოიყენე.",
    source: "core",
    week: 4,
  },
  {
    key: "scope",
    en: "Scope",
    ka: "ფარგლები / მოცულობა",
    explanationKa: "პროექტის ფარგლები — რა შედის და რა არ შედის.",
    pronunciation: "სქოუპ",
    exampleEn: "That's outside the scope of this project.",
    exampleKa: "ეს ამ პროექტის ფარგლებს გარეთაა.",
    example2En: "Let's define the scope clearly.",
    example2Ka: "მოდი ფარგლები მკაფიოდ განვსაზღვროთ.",
    source: "core",
    week: 4,
  },
  {
    key: "align",
    en: "Align",
    ka: "შეთანხმება / გასწორება",
    explanationKa: "მიზნებზე ან გეგმაზე ერთიანი ხედვის გამომუშავება.",
    pronunciation: "ელაინ",
    exampleEn: "Let's align on the next steps.",
    exampleKa: "მოდი შემდეგ ნაბიჯებზე შევთანხმდეთ.",
    example2En: "Our team is fully aligned on the goals.",
    example2Ka: "ჩვენი გუნდი მიზნებზე სრულად შეთანხმებულია.",
    source: "core",
    week: 4,
  },
  {
    key: "scalable",
    en: "Scalable",
    ka: "მასშტაბირებადი",
    explanationKa: "ისეთი სისტემა ან გადაწყვეტა, რომელიც ზრდას უძლებს.",
    pronunciation: "სქეილებლ",
    exampleEn: "We need a scalable solution.",
    exampleKa: "მასშტაბირებადი გადაწყვეტა გვჭირდება.",
    example2En: "This process isn't scalable for a bigger team.",
    example2Ka: "ეს პროცესი დიდი გუნდისთვის არ მასშტაბირდება.",
    source: "core",
    week: 4,
  },
  {
    key: "onboarding",
    en: "Onboarding",
    ka: "ადაპტაცია (ახალი თანამშრომლის)",
    explanationKa: "პროცესი, რომლის დროსაც ახალი თანამშრომელი ეცნობა კომპანიას.",
    pronunciation: "ონბორდინგ",
    exampleEn: "Onboarding usually takes two weeks.",
    exampleKa: "ადაპტაცია ჩვეულებრივ ორ კვირას გრძელდება.",
    example2En: "She's still in onboarding.",
    example2Ka: "ის ჯერ კიდევ ადაპტაციის პერიოდშია.",
    source: "core",
    week: 4,
  },
  {
    key: "outcome",
    en: "Outcome",
    ka: "შედეგი",
    explanationKa: "ქმედების ან პროცესის საბოლოო შედეგი.",
    pronunciation: "აუთქამ",
    exampleEn: "We're happy with the outcome.",
    exampleKa: "შედეგით კმაყოფილი ვართ.",
    example2En: "The outcome of the meeting was positive.",
    example2Ka: "შეხვედრის შედეგი დადებითი იყო.",
    source: "core",
    week: 4,
  },
];

// ---------------- FIELD-SPECIFIC WORDS ----------------

export const FIELD_WORDS: VocabWord[] = [
  // freelance / remote
  {
    key: "retainer",
    en: "Retainer",
    ka: "ყოველთვიური საფასური",
    explanationKa: "ფიქსირებული თანხა, რომელსაც კლიენტი ყოველთვიურად იხდის უწყვეტი მომსახურებისთვის.",
    pronunciation: "რიტეინერ",
    exampleEn: "We work on a monthly retainer.",
    exampleKa: "ვმუშაობთ ყოველთვიური საფასურით.",
    example2En: "The retainer covers up to 20 hours.",
    example2Ka: "საფასური 20 საათამდე მუშაობას ფარავს.",
    source: "field",
    field: "remote_work",
  },
  {
    key: "deliverable",
    en: "Deliverable",
    ka: "მისატანი შედეგი",
    explanationKa: "კონკრეტული პროდუქტი ან დოკუმენტი, რომელიც კლიენტს უნდა ჩაბარდეს.",
    pronunciation: "დელივერებლ",
    exampleEn: "The main deliverable is the final report.",
    exampleKa: "მთავარი მისატანი შედეგი საბოლოო ანგარიშია.",
    example2En: "Here's the list of deliverables for phase 1.",
    example2Ka: "აი პირველი ფაზის შედეგების სია.",
    source: "field",
    field: "remote_work",
  },
  {
    key: "brief",
    en: "Brief",
    ka: "ბრიფი / დავალება",
    explanationKa: "მოკლე დოკუმენტი, რომელშიც კლიენტი აღწერს რა სჭირდება.",
    pronunciation: "ბრიფ",
    exampleEn: "Please send me the project brief.",
    exampleKa: "გთხოვ პროექტის ბრიფი გამომიგზავნე.",
    example2En: "The brief is unclear — I'll ask questions.",
    example2Ka: "ბრიფი არ არის ნათელი — შეკითხვებს დავსვამ.",
    source: "field",
    field: "remote_work",
  },
  // management
  {
    key: "delegation",
    en: "Delegation",
    ka: "დელეგირება",
    explanationKa: "დავალების სხვისთვის გადაცემა შესაბამისი პასუხისმგებლობით.",
    pronunciation: "დელეგეიშენ",
    exampleEn: "Good delegation frees up time for strategy.",
    exampleKa: "კარგი დელეგირება სტრატეგიისთვის დროს ათავისუფლებს.",
    example2En: "She struggles with delegation.",
    example2Ka: "მას უჭირს დელეგირება.",
    source: "field",
    field: "management",
  },
  {
    key: "kpi",
    en: "KPI",
    ka: "ეფექტურობის საზომი",
    explanationKa: "Key Performance Indicator — ციფრი, რომელიც აჩვენებს რამდენად კარგად მუშაობს ვინმე ან რამე.",
    pronunciation: "ქეი პი აი",
    exampleEn: "Let's review the team's KPIs.",
    exampleKa: "გუნდის KPI-ებს მიმოვიხილავთ.",
    example2En: "This KPI dropped last month.",
    example2Ka: "ეს KPI გასულ თვეს დაეცა.",
    source: "field",
    field: "management",
  },
  {
    key: "accountability",
    en: "Accountability",
    ka: "პასუხისმგებლობა",
    explanationKa: "თქვენი ქმედებების შედეგებზე პასუხის გაცემის მზადყოფნა.",
    pronunciation: "ექაუნთებილითი",
    exampleEn: "We value accountability on this team.",
    exampleKa: "ჩვენს გუნდში პასუხისმგებლობა ფასობს.",
    example2En: "Who has accountability for this?",
    example2Ka: "ვის ეკისრება ამაზე პასუხისმგებლობა?",
    source: "field",
    field: "management",
  },
  // marketing
  {
    key: "campaign",
    en: "Campaign",
    ka: "კამპანია",
    explanationKa: "მარკეტინგული აქტივობების კოორდინირებული სერია კონკრეტული მიზნისთვის.",
    pronunciation: "ქემფეინ",
    exampleEn: "Our summer campaign launches in June.",
    exampleKa: "ჩვენი ზაფხულის კამპანია ივნისში იწყება.",
    example2En: "The campaign exceeded expectations.",
    example2Ka: "კამპანიამ მოლოდინი გადააჭარბა.",
    source: "field",
    field: "marketing",
  },
  {
    key: "engagement",
    en: "Engagement",
    ka: "ჩართულობა",
    explanationKa: "რამდენად აქტიურად რეაგირებს აუდიტორია თქვენს კონტენტზე.",
    pronunciation: "ენგეიჯმენთ",
    exampleEn: "Engagement is up 20% this month.",
    exampleKa: "ამ თვეში ჩართულობა 20%-ით გაიზარდა.",
    example2En: "Stories drive more engagement than posts.",
    example2Ka: "სთორიები პოსტებზე მეტ ჩართულობას იძლევა.",
    source: "field",
    field: "marketing",
  },
  {
    key: "conversion",
    en: "Conversion",
    ka: "კონვერსია",
    explanationKa: "მომხმარებლის ქმედება, რომელიც სასურველ შედეგამდე მიდის (მაგ. ყიდვა).",
    pronunciation: "ქონვერჟენ",
    exampleEn: "The new landing page improved conversions.",
    exampleKa: "ახალმა landing page-მა კონვერსიები გააუმჯობესა.",
    example2En: "Our conversion rate is 3%.",
    example2Ka: "ჩვენი კონვერსიის მაჩვენებელი 3%-ია.",
    source: "field",
    field: "marketing",
  },
  // sales
  {
    key: "pipeline",
    en: "Pipeline",
    ka: "გაყიდვების მილსადენი",
    explanationKa: "მომავალი გაყიდვების შესაძლებლობების ნაკადი.",
    pronunciation: "ფაიფლაინ",
    exampleEn: "Our pipeline looks strong for Q3.",
    exampleKa: "ჩვენი pipeline მესამე კვარტალისთვის ძლიერია.",
    example2En: "We need to fill the pipeline with new leads.",
    example2Ka: "pipeline-ი ახალი ლიდებით უნდა შევავსოთ.",
    source: "field",
    field: "sales",
  },
  // finance
  {
    key: "forecast",
    en: "Forecast",
    ka: "პროგნოზი",
    explanationKa: "მომავალი შემოსავლის ან ხარჯის სავარაუდო შეფასება.",
    pronunciation: "ფორქასტ",
    exampleEn: "The forecast for next quarter is positive.",
    exampleKa: "მომდევნო კვარტლის პროგნოზი დადებითია.",
    example2En: "We revised our sales forecast.",
    example2Ka: "გაყიდვების პროგნოზი გადავხედეთ.",
    source: "field",
    field: "finance",
  },
  // project management
  {
    key: "blocker",
    en: "Blocker",
    ka: "შემაფერხებელი",
    explanationKa: "პრობლემა, რომელიც დავალების შესრულებას აფერხებს.",
    pronunciation: "ბლოქერ",
    exampleEn: "I have one blocker — waiting on design.",
    exampleKa: "ერთი შემაფერხებელი მაქვს — დიზაინს ველოდები.",
    example2En: "Let's solve this blocker today.",
    example2Ka: "მოდი დღეს ეს შემაფერხებელი მოვაგვაროთ.",
    source: "field",
    field: "project_management",
  },
];

// Map BusinessField + priorities to keys to fetch the right field words.
export function fieldKeysFor(fields: string[] = [], goals: string[] = []): string[] {
  const keys = new Set<string>();
  fields.forEach((f) => keys.add(f));
  if (goals.includes("remote_work")) keys.add("remote_work");
  if (goals.includes("emails_writing")) keys.add("remote_work");
  return Array.from(keys);
}

export function fieldWordsFor(fields: string[] = [], goals: string[] = []): VocabWord[] {
  const keys = fieldKeysFor(fields, goals);
  if (!keys.length) return [];
  return FIELD_WORDS.filter((w) => w.field && keys.includes(w.field));
}

export const ALL_WORDS: VocabWord[] = [...CORE_WORDS, ...FIELD_WORDS];

export function findWord(key: string): VocabWord | undefined {
  return ALL_WORDS.find((w) => w.key === key);
}

// ---------------- COMMON GEORGIAN MISTAKES ----------------

export type GeorgianMistake = {
  key: string;
  wrong: string;
  right: string;
  explanationKa: string;
  level: 1 | 2 | 3;
};

export const GEORGIAN_MISTAKES: GeorgianMistake[] = [
  {
    key: "interested",
    wrong: "I am interesting in marketing.",
    right: "I am interested in marketing.",
    explanationKa: "'Interesting' = საინტერესო (საგანი). შენ ხარ 'interested' — დაინტერესებული.",
    level: 1,
  },
  {
    key: "age",
    wrong: "I have 25 years.",
    right: "I am 25 years old.",
    explanationKa: "ინგლისურში ასაკზე ვამბობთ 'I am X years old', არა 'I have'.",
    level: 1,
  },
  {
    key: "turn-on",
    wrong: "Please open the light.",
    right: "Please turn on the light.",
    explanationKa: "სინათლე და მოწყობილობები 'turn on/off' — არა 'open/close'.",
    level: 1,
  },
  {
    key: "depend-on",
    wrong: "It depends from the team.",
    right: "It depends on the team.",
    explanationKa: "'Depend' ყოველთვის თხოულობს 'on'-ს, არა 'from'-ს.",
    level: 2,
  },
  {
    key: "listen-to",
    wrong: "I listen the manager carefully.",
    right: "I listen to the manager carefully.",
    explanationKa: "'Listen' ყოველთვის გვჭირდება 'to'-სთან ერთად.",
    level: 2,
  },
  {
    key: "look-forward",
    wrong: "I look forward to hear from you.",
    right: "I look forward to hearing from you.",
    explanationKa: "'Look forward to'-ის შემდეგ ზმნა -ing ფორმაში დგას.",
    level: 2,
  },
  {
    key: "make-vs-do",
    wrong: "I will do a presentation tomorrow.",
    right: "I will give a presentation tomorrow.",
    explanationKa: "პრეზენტაციას 'give' ვაკეთებთ ინგლისურში, არა 'do'.",
    level: 3,
  },
  {
    key: "since-for",
    wrong: "I work here since 3 years.",
    right: "I have worked here for 3 years.",
    explanationKa: "ხანგრძლივობისთვის — 'for' + present perfect. 'Since' კონკრეტული მომენტისთვის (since 2021).",
    level: 3,
  },
  {
    key: "good-at",
    wrong: "She is good in negotiation.",
    right: "She is good at negotiation.",
    explanationKa: "'Good at' — სტანდარტული ფორმა. 'In' აქ არ ჯდება.",
    level: 2,
  },
  {
    key: "advice",
    wrong: "Can you give me some advices?",
    right: "Can you give me some advice?",
    explanationKa: "'Advice' განუთვლადია — მრავლობით რიცხვი არ აქვს.",
    level: 3,
  },
];
