// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get_profile.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get profile",
  description: "Read the signed-in SpeakBusy user's profile: name, English level, learning path, streak, and onboarding status.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb(ctx).from("profiles").select("first_name, display_name, english_level, selected_learning_path, streak, longest_streak, onboarding_completed, level_test_completed, last_activity").eq("id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { profile: data } };
  }
});

// src/lib/mcp/tools/list_vocabulary.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.105.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_vocabulary_default = defineTool2({
  name: "list_vocabulary",
  title: "List vocabulary",
  description: "List the signed-in user's saved vocabulary words (English word, Georgian meaning, example, status).",
  inputSchema: {
    limit: z.number().int().min(1).max(200).optional().describe("Max rows to return (default 50)."),
    status: z.string().optional().describe("Optional status filter (e.g. 'new', 'learning', 'mastered').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = sb2(ctx).from("vocabulary").select("id, english_word, georgian_meaning, example_sentence, status, difficulty, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 50);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { words: data } };
  }
});

// src/lib/mcp/tools/add_vocabulary_word.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.105.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var add_vocabulary_word_default = defineTool3({
  name: "add_vocabulary_word",
  title: "Add vocabulary word",
  description: "Add a new English word with a Georgian meaning to the signed-in user's vocabulary notebook.",
  inputSchema: {
    english_word: z2.string().trim().min(1).describe("The English word or phrase to save."),
    georgian_meaning: z2.string().trim().min(1).describe("Georgian translation / meaning."),
    example_sentence: z2.string().trim().optional().describe("Optional example sentence in English."),
    difficulty: z2.enum(["easy", "medium", "hard"]).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ english_word, georgian_meaning, example_sentence, difficulty }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb3(ctx).from("vocabulary").insert({
      user_id: ctx.getUserId(),
      english_word,
      georgian_meaning,
      example_sentence: example_sentence ?? null,
      difficulty: difficulty ?? null
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `Saved: ${english_word}` }], structuredContent: { word: data } };
  }
});

// src/lib/mcp/tools/list_mistakes.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.105.3";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function sb4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_mistakes_default = defineTool4({
  name: "list_mistakes",
  title: "List mistakes",
  description: "List the signed-in user's recorded English mistakes with corrections and Georgian explanations.",
  inputSchema: {
    limit: z3.number().int().min(1).max(200).optional().describe("Max rows to return (default 30).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb4(ctx).from("mistakes").select("id, original_sentence, corrected_sentence, explanation_ka, tag, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 30);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { mistakes: data } };
  }
});

// src/lib/mcp/tools/get_business_progress.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.105.3";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
function sb5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_business_progress_default = defineTool5({
  name: "get_business_progress",
  title: "Get business English progress",
  description: "Read the signed-in user's business English learning state and recent vocab session stats.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const client = sb5(ctx);
    const uid = ctx.getUserId();
    const [{ data: state }, { data: sessions }] = await Promise.all([
      client.from("business_state").select("state, updated_at").eq("user_id", uid).maybeSingle(),
      client.from("business_vocab_sessions").select("id, total, new_words, review_words, score, completed, completed_at").eq("user_id", uid).order("created_at", { ascending: false }).limit(10)
    ]);
    const payload = { state: state ?? null, recent_vocab_sessions: sessions ?? [] };
    return { content: [{ type: "text", text: JSON.stringify(payload) }], structuredContent: payload };
  }
});

// src/lib/mcp/index.ts
var projectRef = "hmpwjhzrmfyapijikkuc";
var mcp_default = defineMcp({
  name: "speakbusy-mcp",
  title: "SpeakBusy",
  version: "0.1.0",
  instructions: "Tools for the SpeakBusy Georgian-to-English business English learning app. Use these to read the signed-in user's profile and progress, browse or add vocabulary, and review recorded mistakes.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_profile_default, list_vocabulary_default, add_vocabulary_word_default, list_mistakes_default, get_business_progress_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
